Catrobat/Paintroid

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/tools/ResizeToolIntegrationTest.java, Paintroid/src/main/res/values/string.xml
for crowdin: two strings changed
=> name of rectangle tool changed, ResizeToolIntegrationTest fix

Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/FillCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/helper/FillAlgorithm.java
Please talk to me before merging.
=> Small optimizations for the fill algorithm.

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/tools/FillToolIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/FillToolDialog.java
now cursor is only visible when the EditText field for tolerance is clicked
=> fill tool tolerance cursor visibility

Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/PaintroidApplication.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/BottomBar.java, Paintroid/src/main/res/layout-land/activity_welcome.xml, Paintroid/src/main/res/layout-land/islide_getstarted.xml, Paintroid/src/main/res/layout-land/islide_landscape.xml, Paintroid/src/main/res/layout-land/islide_options.xml, Paintroid/src/main/res/layout-land/islide_possibilities.xml, Paintroid/src/main/res/layout-land/islide_welcome.xml, Paintroid/src/main/res/layout-land/main.xml, Paintroid/src/main/res/layout/dialog_text_tool.xml, Paintroid/src/main/res/layout/tool_options.xml
-> XML for tool caption changed
-> Text Tool XML Changed
-> animation for RTL changed
=> RTL Changes

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/BaseIntegrationTestClass.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/MenuFileActivityIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/NavigationDrawerMenuActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/FlipCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/LoadCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/ResizeCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/RotateCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/LayerListener.java
changed order of the new image dialog
added the solution for the command bug of some tools
=> new image dialog order, command bug

Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/GeometricFillTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ImportTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java, Paintroid/src/main/res/layout-land/tool_options.xml
change size in landscape mode
implement overlaybutton in stamp and import tool
=> PAINT-124: Text_tool

Paintroid/src/main/java/org/catrobat/paintroid/ui/TopBar.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/dragndrop/BrickDragAndDropLayerMenu.java, Paintroid/src/main/res/layout/main.xml
open layer menu with button
show layer buttons correct
swap layers while dragging
=> Paint layer bugs

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/stubs/CommandManagerStub.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/command/UndoRedoManager.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/FlipCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/RotateCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/LayerListener.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/FillTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/RedoTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/UndoTool.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/TopBar.java
includes also undo/redo implementations/Bug fixes
=> Paint 155 pocket code integration

Paintroid/build.gradle
This reverts commit 3707d3091180a1333c81881d787937608c62f7de.
=> Revert "Release VersionCode: 19 VersionName: v1.1.17"

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/ArabicNumberFormatTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/stubs/CommandManagerStub.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/colorpicker/RgbSelectorView.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/BrushPickerView.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/TransformToolOptionsListener.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/FillTool.java
Numbering styles vary depending on the region. bidirectional languages numbering style may be implemented by either Hindi digits or Arabic digits.
=> PAINT-169 Numbering style for bidirectional languages

Paintroid/adb_tasks.gradle, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java
Fixed the problem that text would invisible after using the eraser.
=> Paint-175 color chooser after eraser

Paintroid/src/main/java/org/catrobat/paintroid/ui/BottomBar.java
Initially selected tool button flashes 3 times after 1 second (same time as bottom bar animation).
=> PAINT-167: quick initially animate tool option dialog

Paintroid/src/main/res/values/string.xml
This corrects two strings in string.xml (enjoy_pocket_paint and intro_possibilities_text).
=> PAINT-200 Correct strings in intro

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BaseToolWithRectangleShapeToolTest.java, Paintroid/src/main/java/org/catrobat/paintroid/command/UndoRedoManager.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/LayerBitmapCommandImpl.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawingSurfaceListener.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/Tool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/GeometricFillTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurface.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurfaceThread.java
* wait/notify monitor added for drawing thread runnable
* no more CPU utilization when app is idle
* new Tool interface: startTool
=> PAINT-77: drawing surface performance

Paintroid/src/main/java/org/catrobat/paintroid/listener/LayerListener.java
Layer initialization corrected
=> PAINT-213: layout problems with API 18

Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/BrushPickerView.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseTool.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DrawerPreview.java, Paintroid/src/main/res/layout/dialog_stroke.xml
* DrawerPreview only invalidates when brush options or color changes
* DrawerPreview reformated
=> PAINT-212: DrawerPreview stops previewing

Paintroid/src/main/res/layout-land/main.xml, Paintroid/src/main/res/layout/main.xml
fixed fitSystemWindows attributes
=> PAINT-218: layout problems with status bar

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/NavigationDrawerTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/UiInteractions.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/NavigationDrawerMenuActivity.java
* Unified check if image has been modified
* Added functionality tests
* implemented proper function in UiInteractions
=> PAINT-220: Save dialog before activity switch

Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/Multilingual.java, Paintroid/src/main/java/org/catrobat/paintroid/PaintroidApplication.java, Paintroid/src/main/res/values/arrays.xml
* User preferred language is set on every configuration change
* Refactored language selection: PaintroidApplication and Multilingual classes much clearer
* Now new languages or language mappings only need to be adapted in arrays.xml
=> Paint 225 language settings ignored after orientation change

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/LayerListener.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/button/LayersAdapter.java
- Layer button icons are updated when a new image is created
- Espresso test added
=> PAINT-228: layer button icons after new image

Paintroid/src/main/java/org/catrobat/paintroid/listener/BrushPickerView.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/TopBar.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/button/ColorButton.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DrawerPreview.java
- moved OnColorPickedListener to BrushPickerView
- moved OnColorPickedListener from ColorButton to TopBar
=> PAINT-227: DrawerPreview not updated after orientation change

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/rtl/HindiNumberFormatTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/rtl/MultilingualActivityTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/rtl/RtlUiTestUtils.java
=> PAINT-193 Espresso tests for HindiNumberFormatIntegrationTest

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/rtl/ButtonTopLayersRtlLayoutTest.java
=> PAINT-187 Espresso tests for ButtonTopLayers_RTL_LayoutTest

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/CommandManagerImplementation.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/LayerCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/eventlistener/OnLayerEventListener.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/LayerListener.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/button/LayersAdapter.java
added the member "oldLayerPosition" to the deleteLayerCommand and appropriate operations
appropriate test
=> fixed bug of wrong layer order after layer-delete-undo, appropriate test

Paintroid/src/main/res/values/colors.xml, Paintroid/src/main/res/values/style.xml
* Change `colorAccent` color to the default paintroid color
* Remove obsolete styles from `style.xml`
=> PAINT-211: Inconsistent colors in tool options

Paintroid/src/main/res/layout/activity_welcome.xml
* Remove useless `View`
* Remove outdated attributes
=> PAINT-245: Intro buttons at bottom overlap

Paintroid/src/main/java/org/catrobat/paintroid/intro/TapTargetBase.java
* Detect if language is RTL and scroll to the right direction
=> PAINT-251: Intro scrolls to wrong bottombar direction in RTL

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/IntroUtils.java, Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/intro/TapTargetBase.java, Paintroid/src/main/java/org/catrobat/paintroid/intro/helper/WelcomeActivityHelper.java
* Remove unecessary `activity` reference to itself
* Refactor all usages of `isRTL` to provide a context
* Remove unecessary HTML parsing and use unicode character instead
* Refactor modifiers of helper functions to private where possible
* Rename helper functions to provide more info on what it actually does
* Remove unused helper functions
* Refactor `TapTargetRadius` parameter to `DisplayMetrics`
=> PAINT-252: WelcomeActivity skips tutorial in RTL languages

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/NavigationDrawerTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/rtl/NavigationDrawerRtlTest.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
* Close drawer at `START` gravity
* Add tests
=> PAINT-254: DrawerMenu doesn't close on back button

Paintroid/build.gradle, build.gradle
Hi @ThomasSchwengler  
Sorry for the delay !!
I have made a new PR to add Jacoco plugin.
=> PAINT-93: Gradle Code Coverage Plugin

Paintroid/build.gradle, Paintroid/config/pmd.xml, Paintroid/gradle/code_quality_tasks.gradle, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ScrollingViewIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/intro/ViewPagerIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/intro/ViewPagerRtlIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/RectangleFillToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/StampToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/PathCommandTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BaseToolWithRectangleShapeToolTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/CursorToolTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/DrawToolTests.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/FillToolTests.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/ui/LayerTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/ui/PerspectiveTests.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/NavigationDrawerMenuActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.java
* Update Lint ignores
* Update PMD version and rules
* Update android support libraries
* Update tap-target-view
* Fix all new PMD issues
=> Paint-272: Update project dependencies

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/UndoRedoIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/BitmapLocationProvider.java, Paintroid/src/main/java/org/catrobat/paintroid/command/UndoRedoManager.java
* Rewrite robotium tests to espresso
* Fix scale bug that is now covered with a test
=> PAINT-197: Espresso tests for UndoRedoIntegrationTest

Jenkinsfile
- add upload to files.catrob.at if develop branch
- split APK build in own stage
- bring Jenkinsfile closer to catroid
=> JENKINS-188: Jenkinsfile: Improvements

Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolType.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
* Fix transform tool not working after pinch-zoom
=> PAINT-274: Transform tool doesn't crop after zoom

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolSelectionIntegrationTest.java, Paintroid/src/main/res/layout-land/bottom_bar.xml, Paintroid/src/main/res/layout/bottom_bar.xml
* The order of the tools in the toolbar should be:
* Brush - Eraser - Line - Shapes - Fill - Pipette - Cursor - Text - Stamp - Transform - Image
=> PAINT-279 Order of Tools

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/BrushPickerIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/BrushPickerView.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DrawerPreview.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/NumberRangeFilter.java, Paintroid/src/main/res/layout/dialog_stroke.xml
* As with any tool (e.g. shapes) there shouldn't be radiobuttons in the cursor options, but those buttons.
* The stroke width number should be with an input field, that it is possible to edit the number easily.
=> PAINT-282 Cursor

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/EraserToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/EspressoUtils.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolType.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/EraserTool.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/button/ColorButton.java
* It should be possible to change colors while someone uses the eraser. Just without any effect on the eraser itself, but on the next tool the user chooses.
=> PAINT-281 Colors during Eraser

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/FillToolIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/BrushPickerView.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/FillTool.java, Paintroid/src/main/res/layout/dialog_fill_tool.xml
* improve dealing with ColorToleranceEditText, hiding the keyboard
=> PAINT-297 Fill tool

Jenkinsfile, docker/Dockerfile.jenkins
This removes external dependencies and the need of an own docker-hub account.
=> [JENKINS-194] Add Dockerfile for building to repository

Paintroid/src/main/java/org/catrobat/paintroid/PaintroidApplication.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/DialogAbout.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/DialogTermsOfUseAndService.java, Paintroid/src/main/res/layout/dialog_about.xml, Paintroid/src/main/res/layout/dialog_terms_of_use_and_service.xml
* Remove `getVersionName` function, replace with `BuildConfig`
* Clean up AboutDialog and TermsOfUseDialog creation.
=> PAINT-303: Refactor PaintroidApplication

Jenkinsfile
Per Branch / Pull Request only the last 30 builds should be kept.
=> JENKINS-196 Keep only the last 30 builds per branch/pull request

Jenkinsfile
The generated APKs are accessible from the Jenkins jobs, including PR jobs.
=> JENKINS-231 Do not upload APKs from develop to files.catrob.at.

Jenkinsfile
Restructure and better document environment section, which closes a differentiation between Catroid and Paintroid
remove duplicate volume mapping for analytics.settings
remove unused stash
=> JENKINS-188: Cleanup Jenkinsfile

Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
* Broadcast to media library when image gets saved
* Add unit tests
=> PAINT-335: Saved files don't show up on the device

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/CursorToolTest.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.java
* Add commands depending on tool position, not finger/touch position
* Add test to verify this behaviour
=> PAINT-318: Cursor tool should draw when tapped outside

Paintroid/src/main/res/values-it/string.xml
Update for italian translations.
=> PAINT-336: Update strings

Jenkinsfile, Paintroid/build.gradle, build.gradle
Implements dexcount and apksize tracking and displays plots on jenkins
=> PAINTROID-28, JENKINS-237-track-statistics 

Jenkinsfile
=> JENKINS-261 PAINTROID-30 The 'test this please' PR-comment triggers a Jenkins rebuild

.gitignore, Jenkinsfile.releaseAPK, Paintroid/build.gradle, app/build.gradle, docker/Dockerfile.jenkins, fastlane/Appfile, fastlane/Fastfile
- Added signedRelease buildtype and signing credentials via gradle parameters.
- Added Fastfile and install Fastlane via Docker for upload to Google Play Store.
- Added Jenkinsfiles for release via Jenkins Jobs.
=> JENKINS-266 Release pipeline (APK)

Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java, Paintroid/src/main/res/values/colors.xml
- changed the highlight color to complementary color of the accent color used
- made border of tool get a little smaller when pressed
=> PAINTROID-40: Improve shape tool paste feedback

Paintroid/src/main/java/org/catrobat/paintroid/dialog/PermissionInfoDialog.java, Paintroid/src/main/res/values/string.xml
* Make text similar to the catroid permission reasoning text
=> PAINTROID-52: Improve permission reasoning text

Jenkinsfile, app/build.gradle, app/src/main/AndroidManifest.xml
That means they can be installed in parallel.
@ThomasSchwengler please check if the APK created by this PR fits your criteria.
=> JENKINS-293 The Paintroid builds on Jenkins are independent now.

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/StampToolTest.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java
* Fix some warnings in `BaseToolWithRectangleShape`
* Use android long press timeout
* Trigger drawingSurface redraw on stamp operation
=> PAINTROID-54: Set tool position to touch down position on longclick

Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java
counter rotating canvas before adding the drawable
=> PAINTROID-41: icon not rotating anymore

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/DrawingSurfaceLocationProvider.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
https://jira.catrob.at/browse/PAINTROID-57 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-57.svg)
=> PAINTROID-57: Crop/Transform Tool also works with clicks outside the Box

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/StampToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/StampToolTest.java, Paintroid/src/main/java/org/catrobat/paintroid/command/CommandFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java
* Rewrite tests to work without activity
* Refactor functions and function naming for better readability
=> PAINTROID-21: Refactor Tools - Stamp tool

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/UiInteractions.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/TransformToolOptionsViewInteraction.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/CropCommandTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/ResizeCommandTest.java, Paintroid/src/main/java/org/catrobat/paintroid/command/CommandFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/CropCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/ResizeCommand.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/options/TransformToolOptions.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTransformToolOptions.java, Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml, Paintroid/src/main/res/values/string.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/command/implementation/DefaultCommandFactoryTest.java
https://jira.catrob.at/browse/PAINTROID-68 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-68.svg)
=> PAINTROID-68: Transform Tool can now Resize the Image

colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerView.java
* Hide soft keyboard when user changes color picker tabs
=> PAINTROID-77: Color picker soft keyboard

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolFontSpinnerTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolFontSpinnerTestArabic.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/FontArrayAdapter.java
=> PAINTROID-83: Fix preview fonts

docker/Dockerfile.jenkins
Backport of #693 to fix jenkins issues on hotfix and later master branch
=> JENKINS-322 add needed packages for emulator to fix builds

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/IndeterminateProgressDialogIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/IndeterminateProgressDialog.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
* Rewrite IndeterminateProgressDialog to simple alertdialog
* Guard dialogfragment show to avoid crashes
=> PAINTROID-99: Fix dialogfragments crashing app

colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/RgbSelectorView.java
- Cursor reset to last position after EditText update
=> PAINTROID-97: Changing single character in color chooser HEX

Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/main/res/menu/menu_pocketpaint_more_options.xml, Paintroid/src/main/res/values/string.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
- Added rate us button which starts new PlayStore activity or if the PlayStore isn't installed the browser
=> PAINTROID-111: Rate us button

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/StatusbarIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/rtl/ButtonLayersRtlLayoutTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/LayerMenuViewInteraction.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/TopBarViewHolder.java, Paintroid/src/main/res/layout/pocketpaint_layout_top_bar.xml
=> PAINTROID-89 Layer icon in toolbar

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/StatusbarIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/EraserToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ColorPickerViewInteraction.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/PresenterColorPickedListener.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/BottomNavigationViewHolder.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/TopBarViewHolder.java, Paintroid/src/main/res/layout/pocketpaint_layout_bottom_navigation_item.xml, Paintroid/src/main/res/layout/pocketpaint_layout_top_bar.xml, Paintroid/src/main/res/menu/menu_pocketpaint_bottom_navigation.xml, Paintroid/src/main/res/values/dimens.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
=> PAINTROID-88 Colorpicker in toolbar

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MoreOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/MoreOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/OpenedFromPocketCodeNewImageTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/OpenedFromPocketCodeWithImageTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/TopBarViewInteraction.java, Paintroid/src/debug/java/org/catrobat/paintroid/OpenedFromCatroid.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/TopBarViewHolder.java, Paintroid/src/main/res/layout/pocketpaint_layout_top_bar.xml, Paintroid/src/main/res/menu/menu_pocketpaint_more_options.xml, Paintroid/src/main/res/values/string.xml
=> PAINTROID-94 Back to PocketCode Arrow

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MoreOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/MoreOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/UiMatcher.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/OptionsMenuViewInteraction.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/TopBarViewHolder.java, Paintroid/src/main/res/menu/menu_pocketpaint_more_options.xml, Paintroid/src/main/res/values/string.xml
-Added a Link to Pocket Code to the MoreOptionsMenu.
-The link opens the Pocket Code page in the Google Play store 
=> PAINTROID-110 Link to Pocket Code

Jenkinsfile, app/build.gradle
Set archivesBaseName in gradle and changed the Jenkinsfile artifact path.
=> PAINTROID-127: rename apk on jenkins

Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Asking for permission in standalone only.
=> PAINTROID-117: Permission check in standalone only

Jenkinsfile, build.gradle
should work as soon as [this PR](https://github.com/Catrobat/Catroid/pull/3628) in catroid is merged
=> PAINTROID-130 Build Paintroid PR with Catroid develop on Jenkins

build.gradle
=> Release-2.5.0: Upgrade version code and version name

Jenkinsfile.releaseAPK
=> Release-2.5.0: fix release job

build.gradle
=> Release-2.5.1 Upgrade version code and version name

Jenkinsfile.releaseAPK
APK upload to Google Play and AAR upload to bintray.com are independant.
https://jira.catrob.at/browse/PAINTROID-176
=> PAINTROID-176 Separate bintray upload stage in release job

Jenkinsfile.releaseAPK, build.gradle
Release to fix https://jira.catrob.at/browse/PAINTROID-175
=> Release 2.5.1

Paintroid/src/main/res/drawable/ic_pocketpaint_layers.xml
Deleted old Layer xml File and added new Layer xml File
to the code.
=> PAINTROID-178 Changed Layer Icon

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MoreOptionsIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/main/res/menu/menu_pocketpaint_more_options.xml, Paintroid/src/main/res/values/string.xml
Feedback_entry_in_overflow_menu
https://jira.catrob.at/browse/PAINTROID-157
=> PAINTROID-157_Feedback_entry_in_overflow_menu

build.gradle
-updated version code and number
=> release-v2.5.2

build.gradle
=> related to Catroid-615: Add mavenLocal() as a repository

.github/workflows/sync_crowdin_Paintroid.yml, .github/workflows/sync_crowdin_colorpicker.yml, crowdin_Paintroid.yml, crowdin_colorpicker.yml
-added automatic crowdin integration
=> PAINTROID-131 Add bidirectional Crowdin Integration

Paintroid/src/main/AndroidManifest.xml
=> fix Build with Catroid

Paintroid/build.gradle, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MoreOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/MoreOptionsIntegrationTest.java, Paintroid/src/main/AndroidManifest.xml, Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/MyProvider.java, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/main/res/menu/menu_pocketpaint_more_options.xml, Paintroid/src/main/res/values/string.xml, Paintroid/src/main/res/xml/filepaths.xml, app/src/main/AndroidManifest.xml
Added share image button to the overflow menu.
=> Paintroid-158 Add share image button

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/TransformToolOptionsViewInteraction.java, Paintroid/src/main/res/drawable/ic_pocketpaint_tool_resize_adjust.xml, Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml, Paintroid/src/main/res/values/string.xml
=> PAINTROID-154 Add "Auto" to crop icon

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ShapeToolEraseIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ShapeToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/StampToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/TopBarViewInteraction.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BaseToolWithRectangleShapeToolTest.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/controller/DefaultToolController.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithShape.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ShapeTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/options/ToolOptionsViewController.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultToolOptionsViewController.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/TopBarViewHolder.java, Paintroid/src/main/res/drawable/ic_pocketpaint_checkmark.xml, Paintroid/src/main/res/layout/pocketpaint_layout_top_bar.xml, Paintroid/src/main/res/values/string.xml
Added an icon to the code. updates following soon
=> PAINTROID-152 Add Checkmark to confirm tool applications

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTextToolOptionsView.java, Paintroid/src/main/res/layout/dialog_pocketpaint_text_tool.xml
Remove "Done" button from text tool.
=> PAINTROID-186 Remove "Done" button from text tool.

Paintroid/src/main/res/values-de-rDE/string.xml, build.gradle
=> Release 2.5.3

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ScrollingViewIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolSelectionIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/UndoRedoIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/MoreOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/OpenedFromPocketCodeNewImageTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/OpenedFromPocketCodeWithImageTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/IndeterminateProgressDialogIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/EraserToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/FillToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/PipetteToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/StampToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/UiMatcher.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/FillCommandTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/StampToolTest.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java, Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/command/implementation/CompositeCommandTest.java, Paintroid/src/test/java/org/catrobat/paintroid/test/command/implementation/DefaultCommandManagerTest.java, Paintroid/src/test/java/org/catrobat/paintroid/test/controller/ToolControllerTest.java, Paintroid/src/test/java/org/catrobat/paintroid/test/listener/AutoScrollTaskTest.java, Paintroid/src/test/java/org/catrobat/paintroid/test/listener/DrawingSurfaceListenerTest.java, Paintroid/src/test/java/org/catrobat/paintroid/test/model/LayerTest.java, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/LayerPresenterTest.java, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Refactoring unclear tests and fixing as many flaky tests as possible. Wrote a replacement for testBoundingBoxAlgorithm called testBorders. https://jira.catrob.at/browse/PAINTROID-194
=> Paintroid 194 - Check all tests for correct behaviour

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MoreOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOnBackPressedIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java, Paintroid/src/main/java/org/catrobat/paintroid/UserPreferences.java, Paintroid/src/main/java/org/catrobat/paintroid/common/Constants.java, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/JpgInfoDialog.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/OverwriteDialog.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/PngInfoDialog.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/SaveInformationDialog.java, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/LoadImageAsync.java, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/SaveImageAsync.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/main/res/drawable/ic_pocketpaint_dropdown_arrow_modified.xml, Paintroid/src/main/res/drawable/ic_pocketpaint_dropwdown_arrow.xml, Paintroid/src/main/res/drawable/ic_pocketpaint_save_info.xml, Paintroid/src/main/res/layout/dialog_pocketpaint_save.xml, Paintroid/src/main/res/layout/dialog_pocketpaint_save_jpg_sub_dialog.xml, Paintroid/src/main/res/values/string.xml, Paintroid/src/main/res/values/style.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Save image option:
If there is currently no image saved the dialog shows up with the standard values.(filename = "image", format = "jpg")
If there is a saved image the dialog will always show the saved image information.
Save copy option:
The copy option will always show the standard format. ("image5" "jpg");
when opened from catroid(e.g. pocketcode):
the dialog will not show unless you use the option export.
Overwriting:
When the user wants to overwrite an existing file a dialog pops up which will warn the user about it.
Export should work like save copy where the dialog will show the standard filename since it uses the same function as save copy,
Behavior:
Whenever you save an Image a Save dialog shows up where you can choose between
format and if you choose jpg you can then change the …
=> PAINTROID-148: export as jpg + dialog

Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
File size of image highly depends on the format of the image. Png images are not really affected but jpg are because our standard compression format is PNG. Will only implement this for Catroid after implicit saving is merged because there users can't decide in which format they want to save their file. For standalone version this is not necessary because user can choose the desired compression format and if they want to use a JPG compression for a PNG file or vice versa, they should be able to in my opinion. As soon as a file is opened from catroid we are checking the mime type and set the correct compression format.
Behavior can be tested as follows: 
1) Download a .jpg picture, the bigger the better
2) Load it into pocket code
3) Make a copy of the picture and rotate the copy. 
4) Now …
=> PAINTROID-122 Keep image file size after editing

Paintroid/src/main/AndroidManifest.xml, Paintroid/src/main/java/org/catrobat/paintroid/dialog/AboutDialog.kt, Paintroid/src/main/java/org/catrobat/paintroid/dialog/FeedbackDialog.kt, Paintroid/src/main/java/org/catrobat/paintroid/dialog/ImportImageDialog.kt, Paintroid/src/main/java/org/catrobat/paintroid/dialog/LikeUsDialog.kt
=> Hotfix: fixing some warnings in gradle/builds.

Jenkinsfile.releaseAPK
temporary branch to test upload
=> PAINTROID-121 upload mapping.txt to jenkins

Jenkinsfile, docker/Dockerfile.jenkins
This fixes the fastlane not found issue and apk name too long
=> DEVOPS-467 install fastlane in docker

Paintroid/build.gradle, Paintroid/gradle/code_quality_tasks.gradle, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolSelectionIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/intro/IntroIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/PipetteToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/SprayToolTest.kt, Paintroid/src/main/java/org/catrobat/paintroid/command/CommandFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/SprayCommand.kt, Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawingSurfaceListener.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolType.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SprayTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/options/SprayToolOptionsView.kt, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultSprayToolOptionsView.kt, Paintroid/src/main/res/drawable/ic_pocketpaint_tool_spray_can.xml, Paintroid/src/main/res/drawable/pocketpaint_round_rect_shape.xml, Paintroid/src/main/res/layout-land/pocketpaint_layout_bottom_bar.xml, Paintroid/src/main/res/layout/dialog_pocketpaint_spray_tool.xml, Paintroid/src/main/res/layout/pocketpaint_layout_bottom_bar.xml, Paintroid/src/main/res/values/string.xml, Paintroid/src/main/res/values/style.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/listener/AutoScrollTaskTest.java
- Ignored tests that fail because PAINTROID-126 did not adapt tests. Tests should be fixed in a separate ticket
- Added spray can tool with changeable radius.
- Removed Pipette tool from tool selection
- Failing tests pass on local device 
=> PAINTROID-156 spray can tool

README.md
=> Dead Installation Instructions and Google+ link

.github/workflows/sync_crowdin_Paintroid.yml, .github/workflows/sync_crowdin_colorpicker.yml
-automation was still commented out
=> Crowdin Integration Hotfix

Paintroid/build.gradle, Paintroid/config/lint-baseline.xml, Paintroid/src/main/AndroidManifest.xml
=> PAINTROID-215 Fix catroid storage permits 

fastlane/Fastfile
=> PAINTROID-210 upload mapping.txt via fastlane

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTextToolOptionsView.java, Paintroid/src/main/res/color/background_togglebutton.xml, Paintroid/src/main/res/color/textcolor_togglebutton.xml, Paintroid/src/main/res/layout/activity_pocketpaint_main.xml, Paintroid/src/main/res/layout/dialog_pocketpaint_stroke.xml, Paintroid/src/main/res/layout/dialog_pocketpaint_text_tool.xml, Paintroid/src/main/res/values/style.xml
=> PAINTROID-182 move texttool formatting options to top

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTextToolOptionsView.java, Paintroid/src/main/res/color/background_togglebutton.xml, Paintroid/src/main/res/color/textcolor_togglebutton.xml, Paintroid/src/main/res/layout/activity_pocketpaint_main.xml, Paintroid/src/main/res/layout/dialog_pocketpaint_stroke.xml, Paintroid/src/main/res/layout/dialog_pocketpaint_text_tool.xml, Paintroid/src/main/res/values/style.xml
=>  PAINTROID-183 move textsize option to top 

Paintroid/build.gradle, docker/Dockerfile.jenkins
- [] Include the name of the Jira ticket in the PR’s title
=> DEVOPS-480 Increase Android Build version for Paintroid

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/MoreOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java
Minor changes to 2 espresso tests.
https://jira.catrob.at/browse/PAINTROID-219
=> PAINTROID-219: fix save / copy tests

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/ToastFactory.java, Paintroid/src/main/res/values/string.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Added the place in the file system where the image or copy was saved in the bubble.
https://jira.catrob.at/browse/PAINTROID-141
=> PAINTROID-141 No feedback where images are saved or copied to

.github/workflows/sync_crowdin_Paintroid.yml, .github/workflows/sync_crowdin_colorpicker.yml
=> CrowdIn config is not correctly defined

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/FileFromOtherSourceIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/LoadImageAsync.kt, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Fixed loading of images in android 5 and 6
https://jira.catrob.at/browse/PAINTROID-244
=> PAINTROID-244 Cannot load jpg format in Android 5 and 6

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/OverwriteDialog.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/SaveInformationDialog.java, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/SaveImageAsync.kt, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityInteractor.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/main/res/values/string.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java, build.gradle
=> Paintroid 246

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/OverwriteDialog.java, Paintroid/src/main/java/org/catrobat/paintroid/dialog/SaveInformationDialog.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java, Paintroid/src/main/res/values/string.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
https://jira.catrob.at/browse/PAINTROID-246
=> PAINTROID-246 Where file was saved not shown when opened from Catroid

Paintroid/src/main/res/layout/pocketpaint_layout_help_bottom_bar.xml, Paintroid/src/main/res/layout/pocketpaint_slide_intro_tools_selection.xml
Ticket Solve : [https://jira.catrob.at/browse/PAINTROID-247](https://jira.catrob.at/browse/PAINTROID-247)
=> PAINTROID-247 Tool icons in Help screens are black

Paintroid/src/main/AndroidManifest.xml, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
=> PAINTROID-251

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
=> PAINTROID-212: Adapt format to original image

crowdin_Paintroid.yml, crowdin_colorpicker.yml
=> Added manual translation for kab and tw

.github/workflows/sync_crowdin_colorpicker.yml
Fix branch name according to https://github.com/crowdin/github-action/blob/master/README.md
=> Maintenance: Fix color picker CrowdIn branch name

Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolType.kt
Remove central icons in tool selection square
=> PAINTROID-295

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/intro/IntroIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/PipetteToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java, Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawingSurfaceListener.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolType.kt, Paintroid/src/main/res/layout-land/pocketpaint_layout_bottom_bar.xml, Paintroid/src/main/res/layout/pocketpaint_layout_bottom_bar.xml, Paintroid/src/main/res/layout/pocketpaint_layout_help_bottom_bar.xml
Undid the changes that were done in order to exchange the spray can tool icon for the pipette tool icon (https://github.com/Catrobat/Paintroid/pull/813/files) and added a new row for the Pipette tool. 
Also added the pipette tool to the intro/help page.
https://jira.catrob.at/browse/PAINTROID-296
=> PAINTROID-296 Pipette icon additionally in general tool menu

Jenkinsfile, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/LineToolIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/TopBarViewInteraction.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/LineToolTest.kt, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt, Paintroid/src/main/java/org/catrobat/paintroid/controller/DefaultToolController.kt, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/TopBarViewHolder.kt, Paintroid/src/main/res/drawable/ic_pocketpaint_plus_enabled.xml, Paintroid/src/main/res/layout/pocketpaint_layout_top_bar.xml, Paintroid/src/main/res/values/string.xml
most of implementation should work now, still have to test everything and write tests.
Please review the changes by @Electronix1337 in [his PR](https://github.com/Catrobat/Paintroid/pull/1006/).
I've resolved the merge conflicts
=> PAINTROID-305: Adding a connected segment with line tool

Paintroid/build.gradle, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/SaveCompressImageIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/OpenedFromPocketCodeWithImageTest.java, Paintroid/src/main/java/org/catrobat/paintroid/FileIO.kt, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.kt, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/SaveImageAsync.kt, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityInteractor.java, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
- added better image compression
- added tests
=> PAINTROID-149 Better png compression (Research and implementation)

build.gradle
updated androidCompileSdkVersion and androidTargetSdkVersion from 29 to 30
targetSdkVersion and compileSdkVersion were updated from 29 to 30. 
No compatibility issues were found.
=> PAINTROID-357 [🔺URGENT🔺] androidTargetSdkVersion = 30

.gitignore, .idea/codeStyles/Project.xml, Jenkinsfile.screenshots, Paintroid/build.gradle, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/screenshots/CreateMarketingScreenshots.kt, Paintroid/src/debug/AndroidManifest.xml, fastlane/Fastfile, fastlane/Screengrabfile
Creating a Setup for Fastlane Screengrabs to generate Screenshots for Google Play Store and Marketing
To run the test correctly use fastlanes screengrab in ruby shell in the root folder of Paintroid. Screenshots will be generated in the folder fastlane/metadata/..
Only screenshot tests will be automatically run and languages can be changed in the file "fastlane/Screengrabfile"
=> PAINTROID-365 Fastlane Screengrab Setup

fastlane/Screengrabfile
=> PAINTROID-365 Fixing Screengrabfile

Jenkinsfile, docker/Dockerfile.jenkins
=> Fixing Paintroid build with Catroid

fastlane/Screengrabfile
Restricted to languages for which we also have other meta-data (description etc) already translated. Expand again once the metadata have been translated.
=> Maintenance: currently usable Google Play screenshots

app/build.gradle
Modified the build.gradle file modifying the name of the `.apk` file to include the jenkins variables for the pull request branch name and build number.
For local builds, the name will remain unchanged.
Inspect the attached screenshot to confirm it is working like intended
=> PAINTROID-339 TASK: Add PR# and build# to debug apks

Paintroid/src/main/java/org/catrobat/paintroid/FileIO.kt, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
=> Fixing Catroid crash when exiting Paintroid

Paintroid/src/main/res/drawable/ic_pocketpaint_tool_line.xml
Updated icon of line tool.
https://jira.catrob.at/browse/PAINTROID-390
=> PAINTROID-390 Exchange line tool icon

.idea/codeStyles/Project.xml, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/SmudgeToolTest.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SmudgeTool.kt
=> Fixing wrong Class import

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/CatrobatImageIOIntegrationTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MoreOptionsIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/OraFileFormatIntegrationTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/SaveCompressImageIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOnBackPressedIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/SmudgeToolTest.kt, Paintroid/src/main/java/org/catrobat/paintroid/FileIO.kt, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt, Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/CommandSerializationUtilities.kt, Paintroid/src/main/java/org/catrobat/paintroid/common/Constants.kt, Paintroid/src/main/java/org/catrobat/paintroid/dialog/OverwriteDialog.kt, Paintroid/src/main/java/org/catrobat/paintroid/dialog/SaveInformationDialog.kt, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/LoadImage.kt, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/OpenRasterFileFormatConversion.java, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/SaveImage.kt, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt, Paintroid/src/main/res/layout/dialog_pocketpaint_save.xml, Paintroid/src/main/res/layout/dialog_pocketpaint_save_jpg_sub_dialog.xml, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
It is now possible to check if there is any file that corresponds with the given file name to detect if it will override and existing file. 
=> PAINTROID-344 fix changing file ending when saving image

Jenkinsfile, app/build.gradle
Commit into test branch screenshot-fastlane-test to test the screenshot pipe on jenkins before committing the changes into develop.
=> PAINTROID-423 Fix paintroid filenames

Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt, Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/CommandSerializationUtilities.kt, Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/SmudgePathCommandSerializer.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/WatercolorTool.kt
https://jira.catrob.at/browse/PAINTROID-427
- Prevented loading when opened from Catrobat 
- Changed the SmudgePathCommandSerializer 
- Caught KryoException when reading internal save file
=> PAINTROID-427: Very high frequency crash hotfix

Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/api/CorrectStandbyBucketBehaviourTests.kt
Best practices: https://developer.android.com/topic/performance/appstandby
1.I did not find manipulation for putting paintroid into a specific bucket.
2.Checked if Paintroid has a launcher activity: 
Added a test for the launcher activity which checks if our app is in the active bucket when it starts.
3.Paintroid currently does not have Notifications 
4.Similar to point 3
5.Currently I do not believe that Paintroid is split across multiple packages:
-https://developer.android.com/guide/playcore/feature-delivery#dynamic_feature_modules
-https://stackoverflow.com/questions/54227265/how-app-can-be-split-across-multiple-packages
If any of these points are incorrect i will change them.
Please review …
=> PAINTROID-412: Research if Paintroid follows Best Practices for the restrictive Bucket

Jenkinsfile, Jenkinsfile.releaseAPK
=> Fixed Jenkinfiles to dockerhub pull

Jenkinsfile
=> Fixing duplicating filenames  on jenkins

Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SmudgeTool.kt
-deleted responsible lines for the bug
-do not think a test is needed since other tools also do not have similar tests.
=> PAINTROID-428 Color does not update when swapping from smudge tool.

Paintroid/config/detekt.yml, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ColorPickerViewInteraction.java, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/serialization/CommandSerializationTest.kt, Paintroid/src/main/java/org/catrobat/paintroid/FileIO.kt, Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt, Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/CatrobatFileContent.kt, Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/ColorHistorySerializer.kt, Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/CommandSerializationUtilities.kt, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.kt, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/BitmapReturnValue.kt, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/LoadImage.kt, Paintroid/src/main/java/org/catrobat/paintroid/iotasks/WorkspaceReturnValue.kt, Paintroid/src/main/java/org/catrobat/paintroid/model/MainActivityModel.kt, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt, colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorHistory.kt, colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorHistoryView.kt, colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerDialog.kt, colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerView.kt, colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/RgbSelectorView.kt, colorpicker/src/main/res/layout/color_picker_dialog_view.xml, colorpicker/src/main/res/values/strings.xml
=> PAINTROID-389 color picker dialog color history

Paintroid/src/main/res/color/background_togglebutton.xml
https://jira.catrob.at/browse/PAINTROID-522 Change background of text tool buttons.
=> PAINTROID-522 Change background of text tool buttons.

Paintroid/src/main/res/layout/dialog_pocketpaint_spray_tool.xml
Added a empty linear layout so it will behave in the same way as in the other tools.
[PAINTROID-496](https://jira.catrob.at/browse/PAINTROID-496)
=> PAINTROID-496 Spray can tool redesign

Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/CommandSerializer.kt, Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/PaintSerializer.kt
Increased image version to 2 in order to be able to load old save files.
=> PAINTROID-557: Problems with catrobat save files

.github/workflows/sync_crowdin_Paintroid.yml, .github/workflows/sync_crowdin_colorpicker.yml
[PAINTROID-546](https://jira.catrob.at/browse/PAINTROID-546)
Upgraded github-actions version.
=> PAINTROID-546 Crowdin github action is broken

Paintroid/src/main/java/org/catrobat/paintroid/ui/zoomwindow/DefaultZoomWindowController.kt
Added watercolor tool to compatible new to get it working again.
=> PAINTROID-543: watercolor added to compatible_new

build.gradle
=> Release 2.10.0

Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandManager.kt, build.gradle
=> Release 2.10.1

.idea/codeStyles/Project.xml, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BaseToolWithRectangleShapeToolTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BrushToolTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ClipboardToolTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/CursorToolTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/LineToolTest.kt, Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/SprayToolTest.kt, Paintroid/src/main/java/org/catrobat/paintroid/controller/DefaultToolController.kt, Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawingSurfaceListener.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/Tool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BrushTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ClipboardTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/FillTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/HandTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ImportTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/PipetteTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ShapeTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SmudgeTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SprayTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/options/TextToolOptionsView.kt, Paintroid/src/main/java/org/catrobat/paintroid/tools/options/ToolOptionsViewController.kt, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTextToolOptionsView.kt, Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultToolOptionsViewController.kt
[PAINTROID-185](https://jira.catrob.at/browse/PAINTROID-185)
[PAINTROID-597](https://jira.catrob.at/browse/PAINTROID-597)
Continued working from this [PR](https://github.com/Catrobat/Paintroid/pull/1153). Adapted the implementation to work with [PAINTROID-419](https://jira.catrob.at/browse/PAINTROID-419) as seamlessly as possible. Rewrote some tests to work with new implementation and added a few more.
Also fixes 597.
=> PAINTROID-185: Visibility of the text tool settings

Jenkinsfile.releaseAPK, Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandManager.kt, app/build.gradle, build.gradle, gradle.properties
=> Release 2.11.0

Paintroid/src/debug/AndroidManifest.xml, Paintroid/src/main/AndroidManifest.xml, Paintroid/src/main/java/org/catrobat/paintroid/FileIO.kt, Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.kt, Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt, Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt, Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.kt, build.gradle
[PAINTROID-532](https://jira.catrob.at/browse/PAINTROID-532)
- update compile and target versions to 33
- add READ_MEDIA_IMAGES permission
=> PAINTROID-532: Update app for android 13

Paintroid/build.gradle
[PAINTROID-622](https://jira.catrob.at/browse/PAINTROID-622)
I did some research on the problem with the given stack trace and found that it might be a problem with the Kryo library itself. I think updating the version of Kryo that we currently use from "5.1.1" to the latest "[5.5.0](https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-5.5.0)" or at least to "[5.2.1](https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-5.2.1)" where the buffer underflow issue seems to be fixed (And also updating it on Catroids side too, for compatibility reasons) might fix the problem.
On the Kryo Github somebody had an almost similar issue with a buffer underflow and they released a fix for it in Kryo version "[5.2.1](https://github.com/EsotericSoftware/kryo/releases/tag/kryo-par …
=> PAINTROID-622 Crash in CommandSerializer.readFromInternalMemory (BUF)

Jenkinsfile
=> DEVOPS-756 BrowserStack Integration

Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BrushTool.kt, Paintroid/src/main/java/org/catrobat/paintroid/ui/zoomwindow/DefaultZoomWindowController.kt
[PAINTROID-650](https://jira.catrob.at/browse/PAINTROID-650)
Adapted the tool-compatibilities for zoomwindow usage.
=> PAINTROID-650 Zoom window shows wrong background

Jenkinsfile.releaseAPK, build.gradle
=> Release 2.13.0

Jenkinsfile.releaseAPK, fastlane/Fastfile
https://jira.catrob.at/browse/PAINTROID-627
Create App Bundle in JenkinsFile and upload it to Google Play Store via Fastlane.
=> PAINTROID-627 Create App Bundle in addition to APK
