- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/MenuFileActivityIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java
- Paintroid/src/main/java/org/catrobat/paintroid/OptionsMenuActivity.java
Prevent out of memory when returing to Pocket Code by scaling loaded images
MenuFileActivityIntegrationTest now deletes files that were created by the tests
> Save loaded image bug fixed

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/BaseIntegrationTestClass.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/MenuFileActivityIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/tools/LineToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/tools/RectangleFillToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/tools/StampToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/colorpicker/ColorPickerDialog.java
The old code did not have any of the desired effects.
I.e. the color and other stuff was not reset.
One reason was the usage of PaintroidApplication.currentTool.getDrawPaint().
This function returns a new instance of a Paint (new Paint(other_paint)).
The stroke width, the stroke cap and the color are of primitive type in Paint.
This means that the new instance has a copy (!) of these values.
Modifying these values for a new Paint instance does not influence the original instance.
At first I modified getDrawPaint() to not return a copy of Paint and tried
further changes in BaseTool.
Yet none of these changes lead to the desired results.
What works though is to call ColorPickerDialog.getInstance().updateColorChange
directly, which is done now.
For that the updateColorChange function was …
> Reset the color in the tear down of robotium tests.

- Paintroid/build.gradle
- Paintroid/src/main/AndroidManifest.xml
Independent APKs are allowed to be installed without affecting the
current Pocket Paint installation.
This is useful for testers to have different versions installed in parallel.
Automating this process makes it more accessible and allows Jenkins
to provide such independent APKs.
./gradlew -Pindependent assembleDebug
The created Paintroid-debug.apk file has an internal application name
that depends on the current date and time.
The user displayed label is of the form "Paint MMdd HH:mm" in UTC.
Alternatively you can provide an application name yourself:
./gradlew -Pindependent="Paint Design #2" assembleDebug
The application name and the package name are stored as placeholders in
android manifest.
Moreover the test application id is not set manually anymore, since it
is created …
> Automatize the creation of independent APKs.

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/PipetteToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/PipetteToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/PipetteTool.java
* Pipette now uses a buffered bitmap of all merged layers to retrieve color information
* Adapted the existing junit tests
* Added Espresso integration tests
* ~~Added `.externalNativeBuild` to gitignore~~
> Paint-176: pipette selects visible color from all layers

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/intro/ViewPagerIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.java
`WelcomeActivity` now skips the intro when the back button is pressed instead of closing the app.
> PAINT-204: Handle onBackPressed in WelcomeActivity

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/EraserTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/BottomBar.java
* EraserTool
* Simplified, removed unnecessary overrides
* Removed reference to static currentTool
* Changed previousPaint to previousColor to support change of style
* BottomBar
* Restructured to use a ToolType instead of Tool reference
* Mirrored switchTool method and set previous Paint to new Tool
* Restructured onClick and onLongClick methods to improve readability
> PAINT-201: Drawer Preview out of sync

- Paintroid/src/main/java/org/catrobat/paintroid/dialog/colorpicker/ColorPickerDialog.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/GeometricFillTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java
* leaveTool() removes the created listener
* BrushPicker listeners get also removed now
* TextTool uses the color picker listener from base class
> PAINT-222: remove color picker listeners created by tools

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/Multilingual.java
- Paintroid/src/main/java/org/catrobat/paintroid/NavigationDrawerMenuActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.java
- image is not lost anymore when an other activity is started
- therefore reoved save dialog before help and language activity
- IndeterminateProgressDialog is restartet on orientation change
- keyboard gets closed on orientation change (at least for some APIs)
> Paint 226 back to pocket code after activity switch

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolSelectionIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/EspressoUtils.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/UiInteractions.java
- Paintroid/src/main/java/org/catrobat/paintroid/intro/TapTargetBase.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/BottomBar.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/BottomBarHorizontalScrollView.java
- Paintroid/src/main/res/drawable/ic_action_next_item_background.xml
- Paintroid/src/main/res/drawable/ic_action_previous_item_background.xml
- Paintroid/src/main/res/layout-land/bottom_bar.xml
- Paintroid/src/main/res/layout/bottom_bar.xml
- Paintroid/src/main/res/values/colors.xml
- Paintroid/src/main/res/values/dimens.xml
* Fix tests in `ToolSelectionIntegrationTest`
* Put bottom bar arrows in a container to only scale background
* Add two drawables for gradient background
* Set button width to `65dp` from `75dp` to show at least 4 buttons
* Add transparent color to fade to from `custom_background_color`
* Use an unconstrained `scrollTo` action for colorpicker to fix tests failing from color selection
> PAINT-241: arrows overlapping tool icons

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ImportToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ImportTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
* Add new `ImportToolTest` instrumented unit test
* Refactor `BaseToolWithRectangleShape` to improve readability
* Improve readability of `resize` method
* Remove unused functions
* Annotate certain static variables with `@VisibleForTesting`
* Overload `setBitmapFromFile` in `ImportTool`
* Set `mBox` size to bitmap size
* Clamp `mBox` size within `BaseToolWithRectangleShape` bounds
* Refactor `ImportTool` and `StampTool` to use `Context` instead of `Activity`
* Refactor TransformTool
* Remove dead code `DisplayResizeInformationAsyncTask`
* Refactor custom styled toasts to default toasts
> PAINT-239: Set correction aspect ratio to images in import tool

- Paintroid/src/main/res/layout-land/top_bar_elements.xml
- Paintroid/src/main/res/layout/top_bar.xml
* Change `backgroundTint` attribute namespace to use appcompat attribute
* Change `ImageButton` to `AppCompatImageButton` for Intro
Why: the intro doesn't use the whole layout and therefore the
ImageButton won't get replaced to a AppCompatImageButton automatically
* Add Copyright notice
> PAINT-244: Topbar palette icon has wrong tint on api < 21

- Paintroid/src/main/res/layout-land/main.xml
* Remove legacy attribute as it lead to unwanted behaviour on API 17
> PAINT-246: Bottombar fills whole screen in landscape

- Paintroid/src/main/res/layout/bottom_bar.xml
* Added `fill` attribute to `LinearLayout` gravity
> PAINT-247: fix broken bottombar layout

- Paintroid/src/main/res/layout/custom_progress_dialog.xml
* Use a `FrameLayout` instead of a `RelativeLayout`
* Remove unecessary attributes
> PAINT-249: Indeterminate Progress dialog fills too much vertical space

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/PipetteToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/PipetteTool.java
* Add two tests for undo / redo
* Update the cached bitmap on `resetInternalState`
> PAINT-250: Pipette doesn't update on undo / redo

- Paintroid/build.gradle
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/integration/tools/TextToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/listener/TextToolOptionsListener.java
- Paintroid/src/main/res/layout/dialog_text_tool.xml
- Paintroid/src/main/res/values/style.xml
* Remove thirdparty material spinner and replace with stock spinner
* Adapt tests to stock spinner
* Improve layout xml by grouping entries consistently
* Remove unecessary background color in theme
> PAINT-259: Text tool spinner dropdown cut off

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/intro/util/WelcomeActivityIntentsTestRule.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/rtl/util/RtlActivityTestRule.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/EspressoUtils.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/MultilingualActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/PaintroidApplication.java
- Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.java
- Paintroid/src/main/res/values/string.xml
* Remove EspressoUtils setRtl helper function
Instead set shared preferences before activity start and after
activity end.
* Move `updateToChosenLanguage` to `setToChosenLanguage` in
`MultilingualActivity`
* Add missing locales to `LANGUAGE_CODE` array
* Rework String <-> locale conversion code
* Add hardcoded strings for Pashto and Urdu for API < 21
* Set all activites to chosen language before setting content view
> PAINT-253: Language not set correctly on API >= 25

- Paintroid/src/main/AndroidManifest.xml
- Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.java
- Paintroid/src/main/res/drawable/launch.xml
- Paintroid/src/main/res/values-v19/style.xml
- Paintroid/src/main/res/values/style.xml
Current implementation looks like this: https://streamable.com/voxes
There is no overhead in any way, it simply sets a picture as windowBackground and overrides it once the app is started (Same loading time as before).
> PAINT-268: Add a launch screen

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BaseToolWithRectangleShapeToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/GeometricFillTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurface.java
* Use same box values for one full draw call in `BaseToolWithRectangleShape`
* Reduce surfaceview overdraw
* Reduce the madness going on in `StampTool`
* Fix the `StampTool` not showing a highlight box on copying
> PAINT-267: Resolve rectangle tool drawing jitter

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ShapeToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/listener/ShapeToolOptionsListener.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/Tool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithShape.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DrawTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/GeometricFillTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ImportTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/BottomBar.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/Perspective.java
* Save tool instance state in a Bundle
* Works completely for `CursorTool`, `GeometricFillTool` and `TransformTool`
* Works partially for `TextTool`, `StampTool` and `ImportTool`
* Avoid object creation while drawing
* Optimize `drawOverlayBitmap`
- Load bitmap only once at startup
- Draw bitmap directly to canvas
* Avoid calling observers at every draw call in `DrawTool`, `LineTool` and `CursorTool`
* Add a `setCanvasPointToSurfacePoint` function in Perspective to avoid object creation
* Set `clipRect` to drawing surface bounds for `DrawTool`, `LineTool` and `CursorTool`
> Paint-234: Shape tool doesn't remember chosen shape

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/StampToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java
* Save/restore bitmap to/from bundle on orientation change
* Add espresso test for stamp tool
> PAINT-243: Stamp image lost when switching orientation

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/listener/TextToolOptionsListener.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java
* Refactor `TextToolOptionsListener` to a regular class (less singletons)
* Save `TextTool` state in bundle and restore on load
* Add `testStateRestoredAfterOrientationChange` espresso test
> PAINT-269: Save and restore text tool settings on orientation change

- Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolType.java
- Paintroid/src/main/res/values/string.xml
* Add `xliff` annotation to give translators a hint on what they can expect in a `%s`
* Add tool help content for color chooser and layers button
* Use `tools:ignore` instead of `tools:keep`
* Change underline, italic and bold button text to not be translated
> PAINT-266: Correct translations

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ActivityOpenedFromPocketCodeNewImageTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ActivityOpenedFromPocketCodeTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOnBackPressedTests.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/EspressoUtils.java
- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/NavigationDrawerMenuActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/common/Constants.java
- Paintroid/src/main/res/values/string.xml
* Create new class `Constants` and put common string constants there
* Move string constants from `values/string.xml` to `Constants`
* Adapt functions and remove unnecessary `Context` argument
* Remove unused strings
> PAINT-273: Remove string constants from resources

- Jenkinsfile
Run build inside docker container for better isolation of PR builds.
Removed the parallelism due to additional wait times, as the SDK needed to be updated on all slaves.
> JENKINS-101: Run build inside a docker container

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java
* Fix images not loaded with enabled alpha channel
* Add a test to verify that loaded images have a transparency channel
> PAINT-291: Imported images have wrong bitmap format

- .gitignore
- Jenkinsfile
- buildScripts/build_helper_functions.py
- buildScripts/build_helper_run_tests_on_emulator
- buildScripts/build_helper_start_emulator
- buildScripts/build_helper_stop_emulator
- buildScripts/build_step_create_debug_apk
- buildScripts/build_step_install_android_sdk
- buildScripts/build_step_run_static_analysis
- buildScripts/build_step_run_tests_on_emulator__all_tests
- buildScripts/emulator_config.ini
- buildScripts/jenkins-android-helper/LICENSE
- buildScripts/jenkins-android-helper/README
- buildScripts/jenkins-android-helper/android_emulator_helper_functions.py
- buildScripts/jenkins-android-helper/ini_helper_functions.py
- buildScripts/jenkins-android-helper/jenkins_android_cmd_wrapper
- buildScripts/jenkins-android-helper/jenkins_android_emulator_helper
- buildScripts/jenkins-android-helper/jenkins_android_helper_commons.py
- buildScripts/jenkins-android-helper/jenkins_android_sdk.py
- buildScripts/jenkins-android-helper/jenkins_android_sdk_installer
- buildScripts/log_parser_rules
The developer needs to be easily able to run the same build steps on the dev machine like they are run on Jenkins. This requirement includes using the same emulator setting and the same build options like Jenkins.
Therefore the logic of the build steps from the Jenkinsfile is moved to separate script per step ( `buildScripts/build_*`-scripts). Those scripts are capable of running inside a Jenkins build and on a local developer machine. The script are intended to work on Linux/Mac/Windows.
The scripts take care of creating and starting the emulator. The AVD to use can be configured via the `buildScripts/emulator_config.ini`-file.
To avoid external dependencies the Jenkins-Android-Helper: https://github.com/redeamer/jenkins-android-helper (used to handle the SDK installation and the …
> [JENKINS-208] Move build steps to scripts, which run on Jenkins like on the local machine

- Paintroid/gradle/code_quality_tasks.gradle
With gradle 5.0 the setDestination function will only accept File.
The overload/version taking Object is deprecated.
> Avoids gradle warnings.

- Jenkinsfile
- Paintroid/build.gradle
- buildScripts/build_helper_run_tests_on_emulator
- buildScripts/cover2cover.py
The following steps are performed for code coverage:
1) Turn on JaCoCo coverage in build.gradle
2) Run createDebugCoverageReport instead of connectedDebugAndroidTest
to collect the code coverage.
3) Convert the JaCoCo xml report to Cobertura xml report using a script
originally from https://github.com/rix0rrr/cover2cover.
This is done since the JaCoCo Jenkins plugin has multiple issues:
* The Java source is not "found" (listed as found, but not shown in the HMI)
by the Jenkins plugin in combination with Docker-agents.
* The UI is not as usable as the one of the Cobertura plugin.
4) Publish the results using the Cobertura plugin.
> [JENKINS-212] Collect JaCoCo coverage in Jenkins.

- Jenkinsfile
Having the build fail on missing coverage files might distract from the actual
reason, e.g. test-failures.
> Do not fail the build if there is no coverage file.

- Jenkinsfile
- buildScripts/build_helper_run_tests_on_emulator
- buildScripts/build_helper_run_unit_tests
- buildScripts/build_step_run_unit_tests__all_tests
Run local unit tests in separate build step.
Run local unit tests only for debug variant, otherwise the tests run twice (for debug and release) and so they are also reported twice.
Merging of coverage reports are not supported out of the box or via the plugin. So do not report coverage for the unit tests at the moment.
> JENKINS-221: Run unit tests

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ActivityOpenedFromPocketCodeTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ScrollingViewIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolSelectionIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/RectangleFillToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java
deleted tests: 
testExportNotTouchingOriginal() in ActivityOpenedFromPocketCodeTest.java
testSaveLoadedImage() in MenuFileActivityIntegrationTest.java
testScrollingViewRectTool() in ScrollingViewIntegrationTest.java
testToolSelectionStartAnimation() in ToolSelectionIntegrationTest.java
rewritten tests:
testCenterBitmapAfterCropAndUndo() in TransformToolIntegrationTest.java
testEllipseIsDrawnOnBitmap() in RectangleFillToolIntegrationTest.java works without chnging anything
> PAINT 275: rewrite or drop idnored tests

- Jenkinsfile
Currently there are two different NDK behaviors in place (catroid and paintroid combined), one to keep NDK r16b, which was needed because of the removal of armeabi and MIPS support and one to always use the latest NDK, which is the suggestion from the NDK documentations.
Therefore two different SDK locations on the host are currently in place:
NDK r16b  : /var/local/container_shared/android-sdk
NDK latest: /var/local/container_shared/android-sdk-ndk-latest
As android-sdk was used from the beginning and is already 'released' this can't be changed to eg android-sdk-ndk-r16b and must be kept to the previously used value
Previously this differentation was only current between catroid and paintroid, therefore the android-sdk-paintroid mapping was present. As the differentation is now also …
> JENKINS-232: Use different SDK mappings for different NDK versions

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/intro/ActivityRecreationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/intro/util/WelcomeActivityIntentsTestRule.java
- Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.java
* Move page selection handling to `onPageScrollStateChanged`
* This stops the crashes, but after recreation the listeners get discarded.
Switching pages will recreate them, I guess this is still better than
having crashes.
> PAINT-317: Fix crash in WelcomeActivity

- Paintroid/build.gradle
- Paintroid/proguard-rules.pro
- Paintroid/src/debug/AndroidManifest.xml
- Paintroid/src/main/AndroidManifest.xml
- build.gradle
* Mark only debug builds with `multiDexEnabled`
* We actually only need it for androidTest builds
as espresso + support libraries + mockito already need more than 64k functions
* Revert android gradle plugin version back to `3.0.1`
* Add a template proguard config for the `Paintroid` module
* Add the support multidex module to debug builds
* Set the application name to `android.support.multidex.MultiDexApplication`
for debug builds
* Fix Pocket Paint showing up twice in the app selection for images
* Fix some small issues in the manifest files
> PAINT-327: Fix tests not working on api < 21

- Paintroid/build.gradle
- buildSrc/src/main/groovy/org/catrobat/gradle/EmulatorsPluginExtension.groovy
- buildSrc/src/main/groovy/org/catrobat/gradle/Installer.groovy
In contrast to shouldInstallEverythingAbove the install function can be
called at any place in the emulators closure.
> Renames shouldInstallEverythingAbove to install.

- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/colorpicker/HSVColorPickerView.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/KeyboardListener.java
* Add a reusable `KeyboardListener` class that can be queried for the
current keyboard status
* Fixed colorpicker not being drawn on `api >= 28`
* Apparently `api >= 28` still does not support composed shaders, even
though the documentation claims that there would be support.
> PAINT-324: Fix devices with display notch unable to switch tool

- Jenkinsfile
Using "|| true" here would mean that compile errors would not be found.
The original goal of continuing a build for flaky tests is not as important
as detecting compile errors.
Furthermore the build can be continued already when using the ignoreFailures
gradle setting on tests if that really was an issue.
> JENKINS-250 Ensure that build errors are found when running the device tests.

- Jenkinsfile
- build.gradle
The AVDs are recreated for every build anyway.
Thus keeping the AVDs around to clear them on the next build only
increases the harddrive requirements of the slaves.
And since we already had nearly full disks it is better to clean the AVDs.
In the case of Paintroid this safes roughly 820 MB per job.
> JENKINS-252 Clear the AVD store in the workspace after every build.

- build.gradle
Apparently gradle tries to use the dependencies from the first repository offering this file.
The google repo should be the preferred repo.
See https://jenkins.catrob.at/job/Paintroid/job/develop/329/console for an example of a failing build.
> PAINTROID-8: Fix failing jenkins builds due to repo order

- Jenkinsfile
- docker/Dockerfile.jenkins
* Install Android SDK/NDK and packages in Docker image
This makes clear what dependencies are used.
When new SDK/NDK versions are released the Paintroid developers can
decide when to migrate to the newer versions.
This is especially useful when newer versions cause issues,
like the last NDK release.
* Sets ANDROID_SDK_ROOT and ANDROID_HOME inside of the Docker image.
All the other android related environment varaibles are not needed anymore.
* The user inside docker ('user') now has its home placed at '/home/user'
instead of '/'.
This solves many issues:
* Now $HOME is writable and all its content can be read.
* As a result environment variables or paths that are derived from $HOME
work automatically.
* GRADLE_USER_HOME does not need to be set, instead the external gradle
cache is mounted …
> PAINTROID-10, JENKINS-251 Moves many responsibilities to the Dockerfile.

- Jenkinsfile
At the moment there are calls to gradle clean in the Paintroid-Jenkinsfile.
These are unnecessary since git cleans everything in-between builds.
They slow down the build unnecessary.
Remove these clean steps for Paintroid.
> PAINTROID-29 / JENKINS-262: Avoid gradle clean

- Paintroid/src/main/java/org/catrobat/paintroid/contract/LayerContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/LayerAdapter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/dragndrop/DragAndDropListView.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/dragndrop/DragAndDropPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/dragndrop/ListItemLongClickHandler.java
- Paintroid/src/main/res/layout/pocketpaint_layout_main_menu_layer.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/LayerPresenterTest.java
* Handle click and longclick events in the listview instead of the item views
* Disable `SplitMotionEvents` in listview
* Adapt tests
* Invalidate listview on touchup properly
> PAINTROID-2: Fix crash in layer menu

- Jenkinsfile
- docker/Dockerfile.jenkins
The container is only allowed to use 7 GB of RAM and 3.5 CPUs.
With the -XX:+UnlockExperimentalVMOptions and -XX:+UseCGroupMemoryLimitForHeap
Java Option these settings are also respected in Java 8.
Thus Java 8 uses fewer threads and also memory.
With the limited resources the build jobs take slightly longer than without
restrictions. Yet this allows to have two executors per node in the future
and therefore improving overall performance.
Furthermore this can be seen as necessary precondition for parallelisation:
If there are only few executors there are not enough resources to actually
parallelise things.
The container will only run on executors that provide the label LimitedEmulator.
Nodes with this label should either have just one executor or should not provide
the Emulator label. …
> JENKINS-246 Limit resources used by the Paintroid docker container.

- Jenkinsfile
Taken from the story:
* One commit that changes everything to whitespaces.
* Fewer environment variables. Instead use local variables where useful.
* Better stages, i.e. one for tests with sub stages for the different kinds of tests. This makes it easier to parallelize these stages later on.
* Helper functions to make what is used clearer. Especially avoid moving results etc!
build the APKs first and only run the tests afterwards. That way there are also APKs if some tests fail.
* No CPU limitation is needed, as the scheduler will handle that anyway. That way if there is a single job on a slave it uses more CPU automatically.
* 6.5 GB of RAM are sufficient for all containers.
> PAINTROID-47, JENKINS-278 Cleanup Jenkinsfile

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ScrollingViewIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawingSurfaceListener.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurface.java
- Paintroid/src/test/java/org/catrobat/paintroid/test/listener/DrawingSurfaceListenerTest.java
* Ignore clicks starting in range of drawer edges
* This uses the same border width constants as the support library
navigation drawer
* Add unit tests verifying this behaviour
* Adapt espresso tests
> PAINTROID-39: Fix menus slide buggy

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
- tool options are now toggled when auto crop is used
- changed some tests to reopen/stop closing the tool options
- wrote a test expecting the PerformException by clicking the auto crop button a second time without reopening the tool options
-- deleted some commented out code in TransformToolIntegrationTest::testCenterBitmapAfterCropAndUndo?!
> PAINTROID-36: auto crop feedback

- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawingSurfaceListener.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurface.java
- Paintroid/src/test/java/org/catrobat/paintroid/test/listener/DrawingSurfaceListenerTest.java
* Add a `disableAutoScroll` function to drawingSurface and its listener
* Add a unit test to verify the behaviour
* Change `MockitoJUnitRunner` to `MockitoJUnitRunner.silent` to avoid unecessary stubbing warnings
> PAINTROID-55: Disable autoscroll in fullscreen

- Paintroid/src/main/res/layout/dialog_pocketpaint_fill_tool.xml
- Paintroid/src/main/res/layout/dialog_pocketpaint_shapes.xml
- Paintroid/src/main/res/layout/dialog_pocketpaint_stroke.xml
- Paintroid/src/main/res/layout/dialog_pocketpaint_text_tool.xml
- Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml
- Paintroid/src/main/res/layout/pocketpaint_layout_tool_options.xml
- Paintroid/src/main/res/values/style.xml
* Create several style classes to unify the look of our tool option layouts
* Replace all copy pasted xml with the new styles (less code, greater uniformity)
Brush tool layout
=========
| Before | After |
| --------- | ------ |
| <img src="https://user-images.githubusercontent.com/30626927/53683063-cec5b780-3cfc-11e9-8d4d-f86e8a9acd8f.png" width="256" > | <img src="https://user-images.githubusercontent.com/30626927/53683112-75aa5380-3cfd-11e9-8866-3c501b7a004c.png" width="256" > |
Shapes tool layout
===========
| Before | After |
| --------- | ------ |
| <img src="https://user-images.githubusercontent.com/30626927/53683129-a8ece280-3cfd-11e9-8a06-198fa875a008.png" width="256" > | <img src="https://user-images.githubusercontent.com/30626927/53683137-bb671c00-3cfd-11e9-8deb-1637fb66eac2.png" …
> PAINTROID-60: Fix inconsistent padding

- Jenkinsfile
Rename the APKs so that they contain information on the branch and the build.
This makes it easier to track where locally stored APKs came from.
> JENKINS-297: Rename the APKs

- Jenkinsfile
The other static analysis plugins are deprecated and succeeded by warnings-ng.
With JENKINS-55436 fixed we can use warnings-ng ourselves, without breaking
existing jobs.
> JENKINS-269: Use the warnings-ng plugin.

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOnBackPressedIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/FillToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/RectangleFillToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/StampToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/DrawingSurfaceLocationProvider.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/EspressoUtils.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ShapeToolOptionsViewInteraction.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ToolBarViewInteraction.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ToolPropertiesInteraction.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BrushToolTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/FillToolTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ShapeToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/PaintroidApplicationFragment.java
- Paintroid/src/main/java/org/catrobat/paintroid/listener/ShapeToolOptionsListener.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolReference.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BrushTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolReference.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/EraserTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ShapeTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurface.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DrawerPreview.java
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
* Add a `ToolReference` class, replacing the `public static Tool currentTool`
* Rename `DrawTool` to `BrushTool`
* Rename `GeometricFillTool` to `ShapeTool`
* Rename `.*Tests` classes to `.*Test`
* Fix all failing tests and utility test classes
> PAINTROID-1: Fix crash when second MainActivity in same process

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/BrushPickerIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BrushToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/common/CommonBrushChangedListener.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/common/CommonBrushPreviewListener.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BrushTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/options/BrushToolOptions.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/options/BrushToolPreview.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/BrushToolView.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultBrushToolOptions.java
- Paintroid/src/main/res/layout/dialog_pocketpaint_stroke.xml
https://jira.catrob.at/browse/PAINTROID-20 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-20.svg)
https://jira.catrob.at/browse/PAINTROID-18 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-18.svg)
* Move all `View` creation out of `BrushTool` and `EraserTool`
* Rename `DrawerPreview` to `BrushToolView` and extract interface
* Rename `BrushPickerView` to `DefaultBrushToolOptions` and extract interface
* Create reusable `CommonBrushChangedListener` and `CommonBrushPreviewListener` classes
* Refactor `BrushToolTest` to work without an activity
> PAINTROID-20/PAINTROID-18: Refactor brush and eraser tool

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolFontSpinnerTest.java
- Paintroid/src/main/res/values/arrays.xml
https://jira.catrob.at/browse/PAINTROID-59 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-59.svg)
> PAINTROID-59: Sans Serif now default font for Texttool

- Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/common/MainActivityConstants.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
- app/src/main/AndroidManifest.xml
https://jira.catrob.at/browse/PAINTROID-70 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-70.svg)
* Immediately finish intro activity if splitscreen is detected
* Display a toast to notify the user why the intro was closed in main activity
* Clean up unecessary request codes in main activity
* Add tests for new request code
* Add a new string
> PAINTROID-70: Prevent crash in intro

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.java
https://jira.catrob.at/browse/PAINTROID-19 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-19.svg)
* Replace `BrushToolOptions` creation with dependency injection
* No tests needed to adapt, as there are not JUnit tests for this class
------
> PAINTROID-19: Refactor line tool

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/common/Constants.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/colorpicker/RgbSelectorView.java
- Paintroid/src/main/res/layout/color_chooser_layout_rgbview.xml
- Paintroid/src/main/res/values/colors.xml
- Paintroid/src/main/res/values/string.xml
https://jira.catrob.at/browse/PAINTROID-63 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-63.svg)
- TextColor of EditText will turn red if the input is not a valid hex value
- Added a Constant greater than the int value a color can be as a return for not a HEX value
> PAINTROID-63: hex color input

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/CursorToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithShape.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
https://jira.catrob.at/browse/PAINTROID-26 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-26.svg)
* Reuse `CommonBrushChangedListener` and `CommonBrushPreviewListener`
* Create `BrushToolOptions` in `DefaultToolFactory` and hand it to `CursorTool`
* Rewrite `CursorToolTest` class to a proper instrumented unit test, remove references to `MainActivity`
* Use the workspace to calculate the center point for `BaseToolWithShape` instead of using the most complicated way imaginable
-----
> PAINTROID-26: Refactor cursor tool

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/options/TextToolOptions.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTextToolOptions.java
https://jira.catrob.at/browse/PAINTROID-22 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-22.svg)
* Move `TextToolOptions` interface to its own file
* Rename `TextToolOptionsListener` to `DefaultTextToolOptions`
* Move layout inflation into `DefaultTextToolOptions` and hand it to `TextTool` in the constructor
* Adapt creation in `DefaultToolFactory`
* No junit tests were harmed in this PR :angel: (There are none for the text tool)
----------
> PAINTROID-22: Refactor text tool

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ImportToolTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/PipetteToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/PipetteTool.java
https://jira.catrob.at/browse/PAINTROID-23 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-23.svg)
* Rewrite tests for import tool and pipette tool to run without an activity
* As the import tool does not use an UI, this is just refactoring the tests
* Remove code duplication in pipette tool
--------
> PAINTROID-23: Refactor import tool

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/algorithm/JavaCropAlgorithmTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/listener/ShapeToolOptionsListener.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/helper/CropAlgorithm.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/helper/DefaultNumberRangeFilter.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/helper/JavaCropAlgorithm.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/options/TransformToolOptions.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultBrushToolOptions.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultFillToolOptions.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTransformToolOptions.java
https://jira.catrob.at/browse/PAINTROID-27 ![](https://img.shields.io/jira/issue/https/jira.catrob.at/PAINTROID-27.svg)
* Move `JavaCropAlgorithm` out of `TransformTool` and use interface where possible
* Rename `ShapeToolOptionsListener` to `DefaultTransformToolOptions` and use interface where possible
* Rename `NumberRangeFilter` to `DefaultNumberRangeFilter` and use interface where possible
* Adapt `DefaultToolFactory`, handing over the tool options in the constructor
* Refactor callback functions and split boolean arguments into separate functions
* Create separate click listeners for each button in `DefaultTransformToolOptions`
* Rename and move `TransformToolTest` to `JavaCropAlgorithmTest` as these only test the algorithm
* Split up tests into separate smaller ones
All previous …
> PAINTROID-27: Refactor Tools - TransformTool

- Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurface.java
* This might still not completely fix all issues, the locking has
to be reworked in the future
> PAINTROID-102: Fix crash when tool is null in drawingsurface

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java
* Remove calls to `Canvas.clipRect` with deprecated `Region.Op` values
See https://developer.android.com/reference/android/graphics/Canvas#clipRect(android.graphics.Rect,%2520android.graphics.Region.Op)
> PAINTROID-107: Fix crash on Android API >= 28

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- colorpicker/src/main/res/layout/color_picker_layout_rgbview.xml
Took 18 as maxLength because it fits 2 times '#' + HexCode. So it is perfect for copy&paste
> PAINTROID-105 ColorPicker Hex Input too long

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/intro/TapTargetIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/EspressoUtils.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/IntroUtils.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/common/Constants.java
- Paintroid/src/main/java/org/catrobat/paintroid/intro/TapTargetBase.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/Perspective.java
- Paintroid/src/main/res/anim/slide_to_bottom.xml
- Paintroid/src/main/res/anim/slide_to_top.xml
- Paintroid/src/main/res/drawable/ic_pocketpaint_scroll_left_bg.xml
- Paintroid/src/main/res/layout-land/activity_pocketpaint_main.xml
- Paintroid/src/main/res/layout-land/pocketpaint_layout_top_bar.xml
- Paintroid/src/main/res/layout/activity_pocketpaint_main.xml
- Paintroid/src/main/res/layout/pocketpaint_intro_top_bar.xml
- Paintroid/src/main/res/layout/pocketpaint_layout_top_bar.xml
- Paintroid/src/main/res/values/colors.xml
- Paintroid/src/main/res/values/dimens.xml
- Paintroid/src/main/res/values/style.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/ui/PerspectiveTests.java
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerDialog.java
- colorpicker/src/main/res/layout/dialog_color_picker.xml
* Use color picker as fragment
* Add an optional action bar into colorpicker (workaround for our current main activity layout)
* Ensure that the color picker can still be used as a dialog
* Add a pleasing transition animation
* Change top bar size to default android action bar size
> PAINTROID-65: Color picker as fullscreen

- Paintroid/src/main/res/values/style.xml
-changed MoreOptionsMenu to black text on white background
> PAINTROID-118 More options menu should use a light background theme

- docker/Dockerfile.jenkins
Unfortunately the Dockerfile is not working as we have incompatible versions of gem and fastlane at the moment - this is a quick fix to fix this.
However we need to fix the situation to be able to have fastlane for releases again. See Jenkins Ticket https://jira.catrob.at/browse/JENKINS-330 for that (is already in progress)
> JENKINS-366 quickfix disable fastlane installation to fix Dockerfile

- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/PermanentDenialPermissionInfoDialog.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
-changed Permission Dialog texts
-added Link to settings when permission is permanently denied
> PAINTROID-120 Saving while denied storage permission

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/MoreOptionsIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/TopBarViewHolder.java
Added "Rate Us!" button to the removed buttons when opened from catroid.
https://jira.catrob.at/browse/PAINTROID-135
> PAINTROID-135: Rate us button in standalone only

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/RectangleFillToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ShapeToolOptionsViewInteraction.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ShapeTool.java
- Fixed Bug That ShapeTool with Transparent Outline Worked Like in Fill Mode
- added Test to ensure ShapeTool with Transparent Outline Works
> PAINTROID-136 ShapeTool With Transparent Outline Not Working

- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- ColorChooser is no longer fullscreen in Standalone
> PAINTROID-116 ColorChooser not fullscreen

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ShapeToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ShapeToolOptionsViewInteraction.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ShapeTool.java
- Fixed error that ShapeTool with outlineWidth one had width 2 and anti aliasing was turned on
> PAINTROID-134 ShapeTool with width 1 had width 2

- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerDialog.java
-colorpicker now always uses dialog version
> PAINTROID-172 Color Picker consolidation

- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/TopBarViewHolder.java
- Paintroid/src/main/res/layout/pocketpaint_layout_top_bar.xml
- Paintroid/src/main/res/values/style.xml
* Convert the layout containing the toolbar to a AppBarLayout
* Remove previously necessary hacks to emulate the look of a toolbar
* Remove the toolbar title textview and just use the toolbar title (which is already stiled properly)
* Fix button width and heights
* Adapt tests
https://jira.catrob.at/browse/PAINTROID-174
> PAINTROID-174: Fix alignment of undo and redo button

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/options/TextToolOptionsView.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTextToolOptionsView.java
- Paintroid/src/main/res/layout/dialog_pocketpaint_text_tool.xml
Removed strike through option from text tool
> PAINTROID-171: Removed strike through option from text tool

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ShapeToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ShapeTool.java
Shape tool now uses a new Paint again.
> PAINTROID-175: other tools do not work anymore

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/StampToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/DrawingSurfaceInteraction.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java
Changed stamp tool behaviour to only capture current layer contents.
> PAINTROID-137: Stamp tool capture current layer

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java
Deleted all references to background shadow. 
https://jira.catrob.at/browse/PAINTROID-138
> PAINTROID-138: unselected background not dimmed

- Paintroid/build.gradle
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/LayerMenuViewInteraction.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ToolBarViewInteraction.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/model/LayerTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/LayerContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/model/Layer.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/Workspace.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultWorkspace.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/LayerAdapter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/dragndrop/DragAndDropListView.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/dragndrop/DragAndDropPresenter.java
- Paintroid/src/main/res/drawable/ic_pocketpaint_layers_visibility.xml
- Paintroid/src/main/res/layout-land/activity_pocketpaint_main.xml
- Paintroid/src/main/res/layout/activity_pocketpaint_main.xml
- Paintroid/src/main/res/layout/pocketpaint_item_layer.xml
- Paintroid/src/main/res/layout/pocketpaint_layout_main_menu_layer.xml
- Paintroid/src/main/res/values-de-rDE/string.xml
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/model/LayerTest.java
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/LayerPresenterTest.java
Allow to set visibility of layers with checkbox, users are not allowed to merge or reorder when layers are visible due to problems with undo/redo. Users can not choose between different tools while on hidden layer, otherwise the original bitmap would be overwritten.
https://jira.catrob.at/browse/PAINTROID-159
> Paintroid 159 Hide/Unhide Layer

- Paintroid/build.gradle
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOptionsIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ImportToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ImportToolTest.java
- Paintroid/src/main/AndroidManifest.xml
- Paintroid/src/main/java/org/catrobat/paintroid/common/Constants.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/controller/DefaultToolController.java
- Paintroid/src/main/java/org/catrobat/paintroid/controller/ToolController.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/ImportImageDialog.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ImportTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/StampTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/fragments/CatroidMediaGalleryFragment.java
- Paintroid/src/main/java/org/catrobat/paintroid/web/MediaGalleryWebViewClient.java
- Paintroid/src/main/res/drawable/ic_catrobat_logo_black.xml
- Paintroid/src/main/res/layout/dialog_pocketpaint_import_image.xml
- Paintroid/src/main/res/layout/dialog_pocketpaint_webview.xml
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/main/res/values/style.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Added the possibilty for a user to choose between catroid media gallery and his own gallery when importing an image
> PAINTROID-155 Insert image from Catrobat media gallery

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/FileFromOtherSourceIntegrationTest.java
- Paintroid/src/main/AndroidManifest.xml
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
Implemented sharing/editing pictures with Paintroid and the app shows up when the user clicks on any image and tries to share/edit it. A bitmap with the picture will be created (equal to load image) and when user saves the image a new image is saved. When the user clicks on the share/edit button the MainActivity gets invoked and identifies, that someone tries to share data with us. So each time there will be a new instance of the app.
https://jira.catrob.at/browse/PAINTROID-196
> PAINTROID-196 Share images from other apps

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ImportToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ShapeToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/StampToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BaseToolWithRectangleShapeToolTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/CursorToolTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ImportToolTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ShapeToolTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/StampToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/Workspace.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithShape.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultWorkspace.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurface.java
Implemented that perspective scale does not reset when choosing certain tools (text, shape, transform, importpng, stamp) and the tool box gets placed in the middle of the screen if scale > 1 (if zoomed). Also added tests to check behavior for affected tools. https://jira.catrob.at/browse/PAINTROID-139
> PAINTROID-139 Using certain tools should not reset the center and zoom level of the canvas

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/controller/DefaultToolController.java
- Paintroid/src/main/java/org/catrobat/paintroid/controller/ToolController.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/LayerAdapter.java
Implemented applying text/shape/importpng/transform tool when selecting other tool. It will not apply the tool when pressing back, only brush tool will be set. Also wrote 2 tests to test the correct behavior.
https://jira.catrob.at/browse/PAINTROID-147
> PAINTROID-147 - Confirm tool application by selecting another tool

- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/command/CommandManager.java
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/AsyncCommandManager.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
I detected the blinking on every device and API I tested, so implemented that the dialog will only show up for saving images/copies and for importing stickers from catroid gallery
https://jira.catrob.at/browse/PAINTROID-188
> PAINTROID-188 - Obtrusive flicker/blinking whenever stroke or drawing action is performed on Android 10 & 11

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOnBackPressedIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/OpenedFromPocketCodeNewImageTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/OpenedFromPocketCodeWithImageTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/SaveBeforeFinishDialog.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
eliminated the dialog.
Removed the following tests:
testBrushToolBackPressedFromCatroidAndDiscardPicture
testBackToCatroidClickedWhenUndoAvailableAndOpenedFromCatroidThenShowSaveBeforeReturnDialog
Reason: The dialog no longer shows up which means we no longer need these tests.
> PAINTROID-193 Implicit saving of edited image when returning to Catroid

- Jenkinsfile.releaseAPK
- fastlane/Fastfile
This fixes the apk file not found issue in fastlane, due to the filename being wrong.
> DEVOPS-468 fix apk file not found in fastlane

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/OraFileFormatIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/catroid/OpenedFromPocketCodeNewImageTest.java
- Paintroid/src/main/AndroidManifest.xml
- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java
- Paintroid/src/main/java/org/catrobat/paintroid/command/CommandFactory.java
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandFactory.java
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/LoadBitmapListCommand.java
- Paintroid/src/main/java/org/catrobat/paintroid/common/Constants.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/OraInfoDialog.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/SaveInformationDialog.java
- Paintroid/src/main/java/org/catrobat/paintroid/iotasks/BitmapReturnValue.java
- Paintroid/src/main/java/org/catrobat/paintroid/iotasks/LoadImageAsync.java
- Paintroid/src/main/java/org/catrobat/paintroid/iotasks/OpenRasterFileFormatConversion.java
- Paintroid/src/main/java/org/catrobat/paintroid/iotasks/SaveImageAsync.java
- Paintroid/src/main/java/org/catrobat/paintroid/model/LayerModel.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/Workspace.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultWorkspace.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityInteractor.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Saving files as Openraster file format and also being able to load them.
Implemented it into the Save dialog. (https://www.openraster.org/baseline/file-layout-spec.html)
Also added new test class for OraFile testing.
Behaviour: When saving a file you have a new option in the spinner menu called "ora".
It saves layers. And on load opens the layers again. Can also load other ora files created by other application like mypaint.
Apis:
If the api < 29 the picture will be saved in the "normal" image folder. 
otherwise it will be saved into the downloads folder in a subdirectory called "Pocket_Paint" since it 
is not really possible to store it in the image folder. (this was already discussed)
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md …
> Paintroid-160: Create file format .catrobat-image / save/load .catrobat-image.

- app/proguard-rules.pro
changed proguard file to keep line numbers in stacktraces 
> PAINTROID-218 improve stacktrace

- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.java
- Paintroid/src/main/java/org/catrobat/paintroid/common/Constants.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/ScaleImageOnLoadDialog.java
- Paintroid/src/main/java/org/catrobat/paintroid/iotasks/BitmapReturnValue.java
- Paintroid/src/main/java/org/catrobat/paintroid/iotasks/LoadImageAsync.java
- Paintroid/src/main/java/org/catrobat/paintroid/iotasks/OpenRasterFileFormatConversion.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityInteractor.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
- gradle/wrapper/gradle-wrapper.properties
checks how much memory png or jpg files would take and asks to scale them down if it is more than the available memory
evolved from combination with Paintroid-129
> PAINTROID-128

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/SaveInformationDialog.java
Previous default save image format was .jpg, now its .png
Jira-ticket: https://jira.catrob.at/browse/PAINTROID-211
> PAINTROID-211 Changed png to the default image format save option

- Paintroid/src/main/res/drawable/ic_pocketpaint_save_info.xml
- Paintroid/src/main/res/values/style.xml
The ImageButton for format information is visiable again, and dialog text buttons now have a blueish color again.
> PAINTROID-225 Visible format information and blueish dialog text buttons

- Paintroid/build.gradle
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/FileIOTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.java
Ticket Solve: [https://jira.catrob.at/browse/PAINTROID-223](https://jira.catrob.at/browse/PAINTROID-223)
* Used ExifInterface to get orientation flag and rotated bitmap accordingly
* Created test for the same  
> PAINTROID-223: Large images that are scaled down are upside-down (turned by 180 degrees)

- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ZoomableImageView.kt
When selecting a pixel that is exactly the width/height of the bitmap, the `bitmap.getPixel()` function throws a `java.lang.IllegalArgumentException`.
https://jira.catrob.at/browse/PAINTROID-234
> PAINTROID-234 fixed bug when selecting pixel on border

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/SprayToolIntegrationTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultSprayToolOptionsView.kt
After deleting the input from the spray radius text field, it would try to parseInt() this message, resulting in a `java.lang.NumberFormatException`. Also changed the behaviour of the EditTextInput for the radius. Now it behaves like the TextInputs for other tools sizes. Added testcase for empty string.
https://jira.catrob.at/browse/PAINTROID-233
> PAINTROID-233 fixed bug when empty text in spray radius

- Jenkinsfile.releaseAPK
Bintray/jcenter was sunset. Uploads are not possible anymore since the end of March 2021: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Replacement: Generate aar library files via dedicated Paintroid release build stage, then rename and upload them to
https://github.com/Catrobat/Catroid/[..]/catroid/src/main/libs/ 
https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/libs/
> Maintenance: aar instead of bintray

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Where file was saved is now not shown when when handing back looks from Paintroid to Catroid.
https://jira.catrob.at/browse/PAINTROID-246
> PAINTROID-246 Feedback on where file was saved should not be shown in detail when handing back looks from Paintroid to Catroid

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/OverwriteDialog.java
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/SaveInformationDialog.java
- Paintroid/src/main/java/org/catrobat/paintroid/iotasks/SaveImageAsync.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityInteractor.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Where file was saved is now not shown when when handing back looks from Paintroid to Catroid.
https://jira.catrob.at/browse/PAINTROID-246
> PAINTROID-246 Where file was saved not shown when opened from Catroid

- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
Fixed ActivityNotFoundException when the user tries to rate this app but no app is registered for handling the intent.
https://jira.catrob.at/browse/PAINTROID-237
> PAINTROID-237 fixed ActivityNotFound when rating the app

- Paintroid/src/main/java/org/catrobat/paintroid/common/MainActivityConstants.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
Fixed crash when using import image tool without file system access permission on Android 6.0.
https://jira.catrob.at/browse/PAINTROID-250
> PAINTROID-250 Crash when using the "Import image" tool without file system access permission on Android 6.0

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/OraFileIntentTest.java
- Paintroid/src/main/AndroidManifest.xml
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
Ticket solve : [https://jira.catrob.at/browse/PAINTROID-208](https://jira.catrob.at/browse/PAINTROID-208)
- added intent-filter for .ora files
- added test to check intent
- added code to load the image
> PAINTROID-208

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MainActivityIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
Changed parameter `data` in `superHandleActivityResult()` to be nullable. 
https://jira.catrob.at/browse/PAINTROID-252
> PAINTROID-252 nullptr bugfix in superHandleActivityResult

- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- gradle.properties
`FileIO.getBitmapFromUri` might return null or throw `IOException`, also checked for null now.
There was also a bug from the ticket with register intent, when you open an octet-stream/binary file/zip file which is not in the ora file format. Therefore catched the potential `IOException` too, and `importOra()` always returns a `BitmapReturnValue` where the bitmap is null. 
I also increased the jvm heap size, since the statical analysis sometimes goes of of memory when doing the lint checks. 
https://jira.catrob.at/browse/PAINTROID-256
> PAINTROID-256 fixed NPE when image couldn't be decoded

- crowdin_colorpicker.yml
Fix incomplete string resource file names for colorpicker CrowdIn action:
> Maintenance: Fix colorpicker CrowdIn integration

- .github/workflows/sync_crowdin_colorpicker.yml
Add a separate dedicated branch for color picker strings, since previously the two crowdin actions each did a force push and thereby overwrote each other's changes to the same branch.
> Maintenance: Fix color picker CrowdIn integration

- Paintroid/src/main/res/values/string.xml
- Deleted tools:ignore="UnusedResources" which created problems with CrowdIn (strings were not shown to translators anymore and incorrectly are marked as ignore).
- Deleted unused string resources.
- Deleted  translatable="false" for a few strings that _should_ be translated.
Checklist:
> Maintenance: Fix translation issues

- Paintroid/src/main/java/org/catrobat/paintroid/web/MediaGalleryWebViewClient.java
Fixed unexpected behavior with import stickers when clicking on catrobat logo in menu or on "Catrobat community" in the top bar. Now when clicking on one of those two sections, the import interaction will be canceled instead of allowing the user to explore other projects.
Fixed it by regex matching the desired url and in case of the catrobat logo or "catrobat community" in the top bar, the url always is "https://share.catrob.at/pocketcode/" and if that URL is passed to the onPageStarted() function as the "urlClient" parameter, we just call callback.finish().
https://jira.catrob.at/browse/PAINTROID-338
> PAINTROID-338 URGENT: Webview for Import image of Catrobat stickers should not allow to navigate to projects on share

- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/AsyncCommandManager.kt
Tried and fix the crash due to `java.util.NoSuchElementException` when calling `DefaultCommandManager.undo` and `.redo`.
`java.util.NoSuchElementException` is due to popping from the ArrayDeque even after it's empty, so before performing the undo/redo operations, added condition for checking the empty ArrayDeque.
https://jira.catrob.at/browse/PAINTROID-320
> PAINTROID-320 Very high frequency crash in paintroid.[...].DefaultCommandManager.undo and .redo

- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
This PR is basically a small fix/revert for the crashing `testSaveAndOverrideOraFile`.  The `MediaScannerConnection` doesn't seem to save ora files (octet-streams/zip files). However, there was no crash when saving the ora file the first time (it just didn't get saved), but if you try saving it a second time then the testcase would crash because it would look up an URI to a non existent file.
The newer/refactored code (`MediaScannerConnection`) was used because `Intent.ACTION_MEDIA_SCANNER_SCAN_FILE` was deprecated but there is unfortunately not much information out there why it doesn't work with ora (octet-streams/zip files).
(Not jira ticket)
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki …
> Fix for PAINTROID-314 ora files not always getting saved

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerDialog.kt
Now it always updates the color when its changed, and when the cancel button is pressed the color gets changed to its initial color. 
https://jira.catrob.at/browse/PAINTROID-293
> PAINTROID-293 Color picker forgets color when exiting the picker via the back button

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/LineToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ToolPropertiesInteraction.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/LineToolTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/controller/DefaultToolController.java
- Paintroid/src/main/java/org/catrobat/paintroid/controller/ToolController.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/common/Constants.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
https://jira.catrob.at/browse/PAINTROID-228
The new line tool has a checkmark on the right of the top bar. There are several different use cases when the line tool is active:
1. The user can draw a normal line --> I've implemented a threshold and as long as the line is bigger than this threshold, the app detects that the user just wants to draw a normal line and allows that. When finger gets released within the threshold, the line will not be drawn and the last point is set to the starting point. 
2. The user can first declare a start point via a tap, the start point gets marked on the canvas. In order to correctly place the start point the user has the option to correct the initial start point via moving it around until the finger leaves the screen for the first time. When start point is …
> PAINTROID-228 Checkmark for line tool

- Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurface.kt
The crash was most probably due to the missing `catch` block after the `try` in line number 273, so added the `catch` block in the `DrawingSurface` class to possibly fix that crash.
https://jira.catrob.at/browse/PAINTROID-325
> PAINTROID-325 Crash due to java.lang.IllegalArgumentException in DrawingSurface

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/serialization/CommandSerializationTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/CommandSerializationUtilities.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/SerializablePath.kt
In order to smooth the lines the function `cubicTo` was called which wasn't specified for the `SerializePath`.
Also when an  ora-image/catrobat-image/octet-stream is to be opened with Pocket Paint, I think its best to catch every exception, if the user sends a malformed image/etc. This would also catch the crash for https://jira.catrob.at/browse/PAINTROID-321 (but obviously the cause would remain unknown).
https://jira.catrob.at/browse/PAINTROID-351
> PAINTROID-351 Catrobat-image smoothed lines not getting displayed after loading

- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerDialog.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerPreviewActivity.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/FileOperations.kt
The ANR occurs on clicking the `pipette` button when the image is very large due to the use of `runBlocking` which freezes the UI/main thread till the tasks get completed. `runBlocking` is almost never a tool you use in production. It undoes the asynchronous, non-blocking nature of coroutines. So replaced it with `CoroutineScope` in order to obtain the real asynchronous behaviour. As the `storeBitmapTemporally` method is now properly being performed in a background thread, so now the UI isn't frozen and the user could press the `pipette` button multiple times, so to prevent that I disable the button once the user presses it, so this also gives a hint to the user that the button has been pressed and also prevents the user from clicking the button multiple times(which would lead to the …
> PAINTROID-347 ANR in ColorPickerDialog

- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerDialog.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerPreviewActivity.kt
removing coroutines that save and load the image, resulting in freeze.
Previously coroutines were used to temporarily save and restore an image to pass it to the new intent which is started when we click the pipette inside the color picker. The reason most likely was the byte-limitation for extras for new intents.
A static variable was introduced where a bitmap can be passed to the class. If no bitmap is set it will fall back to a colorless 512x512 bitmap to keep the current behavior.
The freeze is now …
> PAINTROID-324 When you load an image and select colour pipette app hangs for a while

- Paintroid/src/main/java/org/catrobat/paintroid/ui/BottomNavigationLandscape.kt
Added Icon.setColorFilter(white) to the setAppearance in the BottomNavigationLandscape.kt file. https://jira.catrob.at/browse/PAINTROID-350
> PAINTROID-350 Color of bottom bar icons is wrong in landscape mode

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/WatercolorTool.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/AlphaSlider.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerDialog.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerView.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/RgbSelectorView.kt
alpha value of slider is now set when changing value of alpha seekbar in RGBSelectorView;
also fixed wrong alpha value when switching between watercolor tool and other tools
(https://jira.catrob.at/browse/PAINTROID-366)
> Paintroid-366 Alpha value on the third tab of color picker is ignored

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/SaveCompressImageIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ToolPropertiesInteraction.java
- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerDialog.kt
Following behaviour was discussed and implemented:
- Apply color changes when the "Apply button" is clicked
- Apply color changes when the "Back button" is clicked
- Apply color changes when the _onCancel_-cethod is called e.g. the user clicks outside the ColorPickerView
- Colors **are not applied** when the "Cancel button" is clicked.
- Color changes should be applied once and only once when the color picker is dismissed and a change has accured.
Older tests have been adjusted to follow the defined behaviour. 
A new test was added to checks the "only apply once"-rule!
One test is currently failing in the pipeline, sadly i can not pinpoint the cause right now.
> PAINTROID-361 Colorpicker permanently sends color to catroid

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/SaveImageProgressBarTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
- Paintroid/src/main/res/layout-land/activity_pocketpaint_main.xml
- Paintroid/src/main/res/layout/activity_pocketpaint_main.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Instead of using the IndeterminateProgressDialog a ContentLoadingProgressBar without DialogFrame is used now.
The IndeterminateProgressDialog was shown and almost immediately afterwards dismissed, which led to flashing of the screen.
The ContentLoadingProgressBar is only shown, if action takes longer than 500ms and then for at least 500ms. 
This prevents the screen from flashing.
https://jira.catrob.at/browse/PAINTROID-142
> PAINTROID-142: No flashing/blinking of the screen when saving or copying images

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/LineToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/BitmapLocationProvider.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/LineToolTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/common/Constants.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
"+" didn't not appear when line was drawn in one swipe
(https://jira.catrob.at/browse/PAINTROID-382)
* setting startpoint plus endpoint and drawing a line was handled differently
* drawing a line in one swipe behaves now like setting startpoint and endpoint separately
* also fixes:
PAINTROID-383: Line tool does not allow to correctly reposition end point of first segment
(https://jira.catrob.at/browse/PAINTROID-383)
> PAINTROID-382: "+" icon not appearing in line tool after drawing the first line segment

- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ZoomableImageView.kt
display variable in ZoomableImageView could be null; null check added
(https://jira.catrob.at/browse/PAINTROID-369)
> PAINTROID-369: Crash NullPointerException: colorpicker.ZoomableImageView

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/LoadBitmapListCommandTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/MergeLayersCommandTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/model/LayerTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandManager.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/MergeLayersCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/RemoveLayerCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/ReorderLayersCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/contract/LayerContracts.kt
- Paintroid/src/main/java/org/catrobat/paintroid/model/LayerModel.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.kt
Added error handling to the LayerModel for invalid index accesses. Errors occured due to concurrency issues - now null types are returned instead of crashing.  All major occurences now have null type handling in place, resulting in silent fails for the relevant commands, leaving a valid state behind.  Command undo's are no handled. Missing tests for the LayerModel have been added.
> PAINTROID-371 IndexOutOfBoundsException paintroid.model.LayerModel.getLayerAt and similar crashes with layers (#3 in Crashes and ANRs)

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/WatercolorToolIntegrationTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
setMaskFilterToNull() method call was somehow missing from the switchTool() method in MainActivityPresenter due to which the maskFilter for the paint was not being reset (i.e. not set to null) after the tool was changed. Added it back.
https://jira.catrob.at/browse/PAINTROID-401
> PAINTROID-401 Watercolor followed by normal brush makes normal brush behave like watercolor

- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt
https://developer.android.com/reference/android/widget/Toast#setGravity(int,%20int,%20int) : Starting from Android Build.VERSION_CODES#R, for apps targeting API level Build.VERSION_CODES#R or higher, this method is a no-op when called on text toasts. It resulted in an error entry in the logs each time the tool is switched.
> Maintenance: Remove no-op method (targetSDK 30)

- Paintroid/src/main/res/layout/dialog_pocketpaint_advanced_settings.xml
- Paintroid/src/main/res/values/style.xml
Updated the layout of the advanced settings dialog such that the switches are aligned to the right side of the dialog.
[https://jira.catrob.at/browse/PAINTROID-362](https://jira.catrob.at/browse/PAINTROID-362)
> PAINTROID-362 advanced settings layout

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.kt
- Paintroid/src/main/java/org/catrobat/paintroid/model/MainActivityModel.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/AlphaSliderView.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerDialog.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerView.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/RgbSelectorView.kt
- colorpicker/src/main/res/layout/color_picker_layout_rgbview.xml
When opened in the formula editor in Catroid, the alpha slider is no longer visible. In the RGB tab, the alpha seekbaar's visibility is also hidden and the hex field shows only RGB numbers (not aRGB as before).
When editing images in Catroid using Paintroid, the visibility of all the elements is as usual in Paintroid.
The Catroid-Paintroid integration issue (due to which the images were not being loaded and saved properly when they were opened for editing from Catroid in Paintroid) is fixed. The condition in the `if` block in the `initializeFromCleanState` method in `MainActivityPresenter` was somehow not correct, fixed that.
https://jira.catrob.at/browse/PAINTROID-378
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki …
> PAINTROID-378 Alpha value selectors should not be shown when using the "color picker"-only in Catroid

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BaseToolWithRectangleShapeToolTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/StampToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawingSurfaceListener.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.kt
- Paintroid/src/test/java/org/catrobat/paintroid/test/listener/DrawingSurfaceListenerTest.java
the end position of tools is not affected anymore by jitter movements of the finger when lifting it
A working implementation from Catroid was used.
In addition, in BaseToolWithRectangleShape a condition was removed, which reset short movements and prohibited precise movements (as shown in the video in the task description).
The jitter movement  in sliders is not being fixed with this pr, there will be a separate ticket.
https://jira.catrob.at/browse/PAINTROID-101
> PAINTROID-101 Correct user intended end position for tools

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/LayerMenuViewInteraction.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/contract/LayerContracts.kt
- Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawerLayoutListener.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/LayerAdapter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/viewholder/LayerMenuViewHolder.kt
- Paintroid/src/main/res/layout/pocketpaint_layout_main_menu_layer.xml
Layer preview lost images after configuration change since `isDrawerLayoutOpen` was not set/restored properly.
So after configuration change the Previews have not been updated because the logic stated that it was not displayed.
[https://jira.catrob.at/browse/PAINTROID-363](https://jira.catrob.at/browse/PAINTROID-363)
> PAINTROID-363 Rotations clear images in layer preview

- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/StampCommand.kt
the DITHER_FLAG led to smoothed edges in stamp tool when stamp was enlarged
removed the DITHER_FLAG and tested it on Android 9 and 11; couldn't find any difference between with and without DITHER
except that the "antialiasing" is fixed 
https://jira.catrob.at/browse/PAINTROID-385
> PAINTROID-385 Antialiasing incorrectly turned on for stamp tool in Android 11

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/SmudgeToolIntegrationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/SmudgePathCommandTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/serialization/CommandSerializationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/SmudgeToolTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/CommandFactory.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandFactory.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/SmudgePathCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/BitmapSerializer.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/CommandSerializationUtilities.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/SmudgePathCommandSerializer.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolType.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SmudgeTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/options/SmudgeToolOptionsView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultSmudgeToolOptionsView.kt
- Paintroid/src/main/res/drawable/ic_pocketpaint_tool_smudge.xml
- Paintroid/src/main/res/layout-land/pocketpaint_layout_bottom_bar.xml
- Paintroid/src/main/res/layout/dialog_pocketpaint_smudge_tool.xml
- Paintroid/src/main/res/layout/pocketpaint_layout_bottom_bar.xml
- Paintroid/src/main/res/layout/pocketpaint_layout_help_bottom_bar.xml
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/controller/ToolControllerTest.java
1. The smudge tool creates a bitmap of the size of the brush on handle down and stores the pixel information from the selected layer.
2. It then stores amortized points in handle move, such that the points lead in the direction of the move, but are layed out at a fixed distance (to ensure that the drawed smudge would not contain any glitching effects).
3. On handle up it creates a new SmudgePathCommand, which then draws the stored bitmap with varying amounts of transparency at each of the stored points location.
The command ensures that the smudge is considered a single operation and can be entirely undone and redone by the user.
The tool also implements the draw function, which is used to preview the drawing of the smudge while the user is dragging the finger on the screen.
There are two …
> PAINTROID-292 Smudge tool

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/BaseToolWithRectangleShapeToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ShapeTool.kt
* decreased the minimum box size from 20 to 3 (smaller than 3 doesn't provide good results)
* adapted ShapeTool offset calculation for high zoom levels as margin was too high
https://jira.catrob.at/browse/PAINTROID-408
> PAINTROID-408 Remove minimum size limitation of selections

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LayerIntegrationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/LayerMenuViewInteraction.java
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/CropCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandManager.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/FillCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/contract/LayerContracts.kt
- Paintroid/src/main/java/org/catrobat/paintroid/model/Layer.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/LayerAdapter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/dragndrop/DragAndDropListView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/dragndrop/DragAndDropPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/dragndrop/ListItemDragHandler.kt
- Paintroid/src/main/res/drawable/ic_pocketpaint_drag_handle.xml
- Paintroid/src/main/res/layout/pocketpaint_item_layer.xml
- Paintroid/src/main/res/layout/pocketpaint_layout_main_menu_layer.xml
- Paintroid/src/main/res/values/colors.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/command/implementation/FillCommandTest.java
- Paintroid/src/test/java/org/catrobat/paintroid/test/model/LayerTest.java
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/LayerPresenterTest.java
Deviated a little bit from the suggested design because layers are now displayed according to their aspect ratio, which makes the preview really small, if the layers height is greater than the width. This makes sense because in ticket [PAINTROID-283](https://jira.catrob.at/browse/PAINTROID-283) a seekbar for the alpha value of the layer will be introduced. The seekbar should then be implemented horizontal instead of vertical to avoid a compressed seekbar.
> PAINTROID-199 simplify layer moving and merging

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/serialization/CommandSerializationTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/CommandFactory.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandFactory.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/TextToolCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/SerializableTypeface.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/TextToolCommandSerializer.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/FontType.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/options/TextToolOptionsView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTextToolOptionsView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/FontListAdapter.kt
- Paintroid/src/main/res/layout-land/activity_pocketpaint_main.xml
- Paintroid/src/main/res/layout/pocketpaint_item_layer.xml
Made the texttool draw directly on the canvas instead of generation a bitmap and scaling it accordingly.
Has the side effect that scaled text is no longer blurry.
Introduces a new enum for Fonts to standardize the FontTyppe across the project.
> PAINTROID-82 Text tool has high memory usage

- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.kt
- Paintroid/src/main/java/org/catrobat/paintroid/model/MainActivityModel.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
- added code to check the app version when it starts (in MainActivity)
- used SharedPreferences to remember if help menu was already shown after clean install
- removed dead code left over from the previous implementation
https://jira.catrob.at/browse/PAINTROID-375
- [ x] Include the name of the Jira ticket in the PR’s title
- [x ] Include a summary of the changes plus the relevant context
- [ x] Choose the proper base branch (*develop*)
- [x ] Confirm that the changes follow the project’s coding guidelines
- [x ] Verify that the changes generate no compiler or linter warnings
- [x ] Perform a self-review …
> Paintroid-375: Show help dialog after install of a release version

- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Removed all setInitialAnimationPlayed as well as 1 parameter for each presenter.restoreState() function in the MainActivityPresenterTest class as the initialAnimationPlayed boolean was still in there but signature of function was already changed.
> HOTFIX-Fix_Jenkins_Build

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ImportToolTest.java
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Added 2 Tests, 1 for checking whether bitmap will be downscaled when not enough memory is present while importing and the other checks if the scale dialog will be displayed when not enough memory is present while importing. 
Original PR is https://github.com/Catrobat/Paintroid/pull/846 where tests were not added.
https://jira.catrob.at/browse/PAINTROID-230
> PAINTROID-230 Add tests whether memory check for rescaling works

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/Workspace.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultWorkspace.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.kt
Fixed bug where zoom level and placement were reset after clicking checkmark when using Transformtool. Now zoom level and placement stays the same when transforming via checkmark.
Also deleted and simplified some tests which are not needed anymore and added a test which checks desired behavior.
https://jira.catrob.at/browse/PAINTROID-415
> PAINTROID-415 Keep zoom level and placement after applying the Transform tool

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/PipetteToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ColorPickerPreviewInteraction.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ColorPickerViewInteraction.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/SmudgeToolTest.kt
- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerPreviewActivity.kt
implemented new tests for ColorPicker Pipette.
-new class for the ColorPickerPreview when using the Pipette in the color picker.
-new method in ColorPickerViewInteraction for clicking on the pipette button.
-changed some headers in project files
-removed ignore from ignored pipette tests which seem to work on jenkins
> PAINTROID-239: PipetteToolIntegrationTests

- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/Perspective.kt
After this ticket when user clicks fullscreen, the bitmap is maxed out as good as possible. Also fixed bug where the bitmap was not centered after exiting fullscreen mode. Also fixed bug of loading temporary image, as developer forgot to set the according bitmap width and height and those were always set to the default display ratios which messed up the perspective/zoom level.
https://jira.catrob.at/browse/PAINTROID-418
> PAINTROID-418 Fullscreen mode should zoom to fit

- colorpicker/src/main/res/layout/color_picker_layout_rgbview.xml
changed the color of word alpha in ColorPicker RGB View to increase the contrast.
[https://jira.catrob.at/browse/PAINTROID-397](https://jira.catrob.at/browse/PAINTROID-397)
> PAINTROID-397 contrast of word alpha

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ClippingToolIntegrationTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/controller/DefaultToolController.kt
- Paintroid/src/main/java/org/catrobat/paintroid/controller/ToolController.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/LayerAdapter.kt
- colorpicker/src/main/res/values/colors.xml
Rewrote some parts of switchTool structure in order to highlight(set the color border to orange) the box (of BaseToolWithRectangleShape) for 300 milliseconds before actually switching the tool.
https://jira.catrob.at/browse/PAINTROID-445
> PAINTROID-445 Give feedback of changed canvas when changing tools

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.kt
- Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.kt
- Paintroid/src/main/java/org/catrobat/paintroid/dialog/SaveInformationDialog.kt
- Paintroid/src/main/java/org/catrobat/paintroid/iotasks/SaveImage.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityInteractor.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt
- Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
Overwrite adding (1) suffix to file names has been fixed for all file formats. I also implemented tests for it.
Additional changes:
- changed the file info parsing after loading an image and save image dialogue file format selection to use the new FileType values in FileIO.kt.
- removed the now obsolete variable isCatrobatImage in FileIO.kt to avoid confusion with new FileType vlaues.
- the "save image" option now displays the name and format of the currently loaded image
Ticket: https://jira.catrob.at/browse/PAINTROID-323
> PAINTROID-323: Overwrite adds suffix after filetype, it should be before .png

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/TransformToolOptionsViewInteraction.java
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultToolOptionsViewController.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTransformToolOptionsView.kt
- Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml
-changed the text field next to the seekbar in the transformtool to edittext. 
The user now can change the exact percentage value.
> PAINTROID-406 Set exact slider value

- colorpicker/src/main/java/org/catrobat/paintroid/colorpicker/ColorPickerView.kt
Fixed Keyboad does not hide after leaving RGB-View
> PAINTROID-486 Keyboad does not hide after leaving RGB-View

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOptionsIntegrationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ClipboardToolIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/ClipboardToolViewInteraction.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/ClipboardCommandTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/serialization/CommandSerializationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ClipboardToolTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/command/CommandFactory.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/ClipboardCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandFactory.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/ClipboardCommandSerializer.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/CommandSerializer.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/ToolType.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ClipboardTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ImportTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/options/ClipboardToolOptionsView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultClipboardToolOptionsView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/zoomwindow/DefaultZoomWindowController.kt
- Paintroid/src/main/res/drawable/ic_pocketpaint_tool_clipboard.xml
- Paintroid/src/main/res/drawable/ic_pocketpaint_tool_stamp.xml
- Paintroid/src/main/res/layout-land/pocketpaint_layout_bottom_bar.xml
- Paintroid/src/main/res/layout/dialog_pocketpaint_clipboard_tool.xml
- Paintroid/src/main/res/layout/pocketpaint_layout_bottom_bar.xml
- Paintroid/src/main/res/layout/pocketpaint_layout_help_bottom_bar.xml
- Paintroid/src/main/res/values/string.xml
- Paintroid/src/test/java/org/catrobat/paintroid/test/controller/ToolControllerTest.java
PAINTROID-494 Change toolbaricon of stamp tool
Refactor project and adapt to renaming of stamp tool to clipboard.
[PAINTROID-494](https://jira.catrob.at/browse/PAINTROID-494)
> PAINTROID-494 Change toolbaricon of stamp tool

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BrushTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SmudgeTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/options/BrushToolOptionsView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultBrushToolOptionsView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultSmudgeToolOptionsView.kt
Added functionallity to set the correct chip of the stroke ChipGroup when choosing a tool.
[PAINTROID-497](https://jira.catrob.at/browse/PAINTROID-497)
- [] Include reasonable and readable tests verifying the added or changed behavior
> PAINTROID-497 Tool stroke-tip type

- Paintroid/build.gradle
- Paintroid/src/main/AndroidManifest.xml
- build.gradle
- colorpicker/src/main/AndroidManifest.xml
In order to update the AndroidTargetSdkVersion to 31, the android:exported needed to be set explicitly in the AndroidManifest.xml files and androidx.test.ext:junit had to be updated from v1.1.1 to v1.1.3.
Jira Ticket: https://jira.catrob.at/browse/PAINTROID-484
> PAINTROID 484 Migrate to targetSDKVersion 31

- Paintroid/src/main/res/color/background_color_chip_state_list.xml
- Paintroid/src/main/res/values/colors.xml
- colorpicker/src/main/res/values/colors.xml
https://jira.catrob.at/browse/PAINTROID-399
Added new colors according to the ticket. However it was not possible to change the color of the Color Picker Tab Icon with this since the icon is an image must be dealt separately. Furthermore the Color Picker Transparent Color which used a checkered grey-white image, which was also noticed by Google for contrast issues, was not adressed in the mock-ups in the ticket. However it is worth mentioning for future tickets.
> PAINTROID-399 Fix contrast of text color to background color

- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/PaintSerializer.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/WatercolorTool.kt
The cause of this issue was that during serializing process of the paint no information about the maskFilter was saved. After closing and opening the app again the correct pathcommand was executed, but due to lack of information the maskFilter was not applied. 
Fix: added boolean value to indicate whether the path had a maskFilter and one int value (alpha) to calculate the range of the maskFilter in the serialization process. After deserializing, this data can be read and the maskFilter can be applied.
[PAINTROID-482](https://jira.catrob.at/browse/PAINTROID-482)
> PAINTROID-482 Watercolor paths loose their translucent mask after load

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOptionsIntegrationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/BrushPickerIntegrationTest.java
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/wrappers/BrushToolOptionsViewInteraction.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultBrushToolOptionsView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultSmudgeToolOptionsView.kt
[PAINTROID-548](https://jira.catrob.at/browse/PAINTROID-548)
Fixed the bug using isChecked value from button element instead of isSelected. IsSelected is [inherited from the View](https://developer.android.com/reference/android/view/View) and does not update the checked state of the Chip correctly. Created a new wrapper BrushToolOptionsViewInteraction for writing new tests and updated old tests to use isChecked instead of isSelected.
> PAINTROID-548 : Selecting the already selected stroke type unselects it

- Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawingSurfaceListener.kt
[PAINTROID-545](https://jira.catrob.at/browse/PAINTROID-545)
Fixed the bug, zooming while drawing with cursor does not delete the already drawn line anymore
> PAINTROID-545 Zooming while cursor tool is down deletes the already drawn line

- Paintroid/src/main/java/org/catrobat/paintroid/ui/zoomwindow/DefaultZoomWindowController.kt
Non-drawing tools show old stroke in zoomed in window
[PAINTROID-526](https://jira.catrob.at/browse/PAINTROID-526)
> PAINTROID-526 Non-drawing tools show old stroke in zoomed in window

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
PAINTROID-519 Changing stroke-tip type triggers undo action
[PAINTROID-519](https://jira.catrob.at/browse/PAINTROID-519)
> PAINTROID-519 Changing stroke-tip type triggers undo action

- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandManager.kt
[PAINTROID-498](https://jira.catrob.at/browse/PAINTROID-498)
Bug:
When chaning StrokeWidth of LineTool, the methode `commandManager.undoIgnoringColorChangesAndAddCommand(command) ` (LineTool.kt) is called.  `undoIgnoringColorChangesAndAddCommand` then calls ` separateColorCommandsAndUndo()` in order to remove the (only most recent?) `ColorChangedCommands`. But since only the commands from top of the deque are removed, there still can potentially be other "older" `ColorChangedCommands` left in the `undoCommandList`. So when ` separateColorCommandsAndUndo()`  calls `handleUndo()`, the older `ColorChangedCommands` are executed and the color property of `ToolPaint` is changed.  And due to many triggers of `CommonBrushChangedListener` while changing the StrokeWidth, …
> PAINTROID-498  Line Color Changing

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/CatrobatImageIOIntegrationTest.kt
[PAINTROID-504](https://jira.catrob.at/browse/PAINTROID-504)
The problem was that the test assumed that the overwrite view will pop up but it won't happen because before the test, there shouldn't be the same file already on jenkins, so there won't be a pop up asking if you want to overwrite. It just saves it and is done.
File also gets cleaned up now after executing the test.
> PAINTROID-504 Fix CatrobatImageIOIntegrationTests

- Paintroid/build.gradle
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MenuFileActivityIntegrationTest.kt
- build.gradle
The MediaStore content provider failed to retrieve the latest file name in the android API 28. Which caused the "ComparisonFailure" exception.
Fixed it by replicating from testSameFileNameAfterOverwritePng where the URI is directly extracted from the savedPictureUri and File class and thereby eliminating the reliability on the content provider.
> PAINTROID-505 Fixed MenuFileActivityIntegrationTests

- Paintroid/build.gradle
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/SaveCompressImageIntegrationTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/FileIO.kt
- build.gradle
PAINTROID-506
SaveCompressImageIntegrationTest failed as testSaveImage() didn't receive appropriate compressed bitmap
Fix:
- load_image action was performed which was uneccesary for this test.
- DecodeBitmapFromUri failed to provide compressed bitmap so replaced it with getScaledBitmapFromUri() to  return a downscaled bitmap that can be loaded efficiently into the memory
- Matchers.equalTo() only accepts bitmap of 1280 X 720 but compressed bitmap could be anywhere below them so changed it to Matchers.lessThanOrEqualTo()
> PAINTROID-506 Fixed SaveCompressImageIntegrationTests

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/ToolOnBackPressedIntegrationTest.java
[PAINTROID-507](https://jira.catrob.at/browse/PAINTROID-507)
Both Tests work locally and on Jenkins now too.
1) testBrushToolBackPressedFromCatroidAndUsePicture:
There was a problem with the waitFor()'s being too short or not consistent on Jenkins so the test didn't reach the state that it was supposed to reach before performing an action. Also had problems with performing actions too quickly after a file save, so the file save was probably not done yet, because the time was too short.
2) testBrushToolBackPressedWithSaveAndOverride:
Basically same problem as described above.
> PAINTROID-507 Fix ToolOnBackPressedIntegrationTests

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/TemporaryFileSavingTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
[PAINTROID-523](https://jira.catrob.at/browse/PAINTROID-523)
Called `presenterMain.saveNewTemporaryImage()` in the `onWindowFocusChanged`  and `onDestroy` callback. Now everytime the app is closed the temporary is saved an no progress is lost for the user. Also added new test case.
> PAINTROID-523 - Image not persistent after closing app

- Paintroid/src/main/java/org/catrobat/paintroid/model/LayerModel.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/DrawingSurface.kt
[PAINTROID-605](https://jira.catrob.at/browse/PAINTROID-605)
In the `DrawingSurface.doDraw` method, each layer is drawn to the bitmap with the opacity set before drawing. Originally, a `null` value was passed as the `Paint` parameter to `canvas?.drawBitmap()`. However, in a later implementation, a `Paint` object with an alpha value was introduced to allow for varying levels of transparency. However, the `Paint`object by default had a filter enabled, which made the stroke appear blurry.
To fix this issue, set `isFilterBitmap` of the `Paint`object to `false`.
> PAINTROID-605 When fully zoomed in drawings are pixelated

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/CommandSerializer.kt
[PAINTROID-429](https://jira.catrob.at/browse/PAINTROID-429)
The model was overwritten twice in the `onCreateMainView` method of the `MainActivity.kt`class. Therefore the actual ColorHistory was always written to the wrong model instance and never to the one in the CommandSerializer. Since the ColorHistory is only written to memory if the model in the CommandSerializer is not empty, it was never written at all.
Fix: Instanciate only one model and read ComandHistory only if there was one written before (if some bytes are left after reading CommandManagerModel from memory) 
Note:
- Fixed testIfRGBSeekBarsDoChangeColor which was failing because of [PAINTROID-397](https://jira.catrob.at/browse/PAINTROID-397).
- Added file cleanup for ColorDialogIntegrationTest
> PAINTROID-429 Kryo does not correctly read files from autosave sometimes

- Paintroid/src/main/java/org/catrobat/paintroid/ui/Perspective.kt
- Paintroid/src/test/java/org/catrobat/paintroid/test/ui/PerspectiveTests.kt
[PAINTROID-606](https://jira.catrob.at/browse/PAINTROID-606)
Opening keyboard resizes the app window by default and changes the vertical center of DrawingSurface. This moved the canvas up or down depending on whether the keyboard is opened or closed. Fixed it by ignoring centerY changes of  DrawingSurface.
> Paintroid-606 Opening the keyboard changes drawing surface position

- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandManager.kt
[PAINTROID-602](https://jira.catrob.at/browse/PAINTROID-602)
This check should fix the bug now in case an access to an element of the undoCommandList happens and the element does not exist..
> PAINTROID-602 Fix "Crash in DefaultCommandManager"

- Paintroid/src/main/java/org/catrobat/paintroid/contract/LayerContracts.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/LayerAdapter.kt
[PAINTROID-466](https://jira.catrob.at/browse/PAINTROID-466)
I tried to reproduce the bug, but didn't manage to reproduce it as there is also no description on how to reproduce it.  The getLayerItem() is now checked in case we try to access a position that is out of bounds, to avoid the app from crashing in case the bug would occur. I also adapted the code parts where the getLayerItem() is called, in case the method would return null.
This should then hopefully eliminate the problem.
> PAINTROID-466 Crash ArrayIndexOutOfBoundsException at LayerPresenter.getLayerItem

- Paintroid/src/main/java/org/catrobat/paintroid/model/LayerModel.kt
[PAINTROID-614](https://jira.catrob.at/browse/PAINTROID-614)
Using the LineTool too fast sometimes crashed the App. 
The reason for the crash seemed to be related to the forEach-Loop that is called in drawLayersOntoCanvas(). Sometimes the forEach tried to iterate out of bound, when using the tool too fast, causing a NoSuchElementException.
It seemed to be a problem with the locking, causing a race condition. I made the method getBitmapOfAllLayers() where the drawLayersOntoCanvas() is called Synchronized and synchronized the LayerModel too, and I didn't manage to reproduce the crash anymore with locking these ressources.
> PAINTROID-614 Using LineTool too fast crashes app sometimes

- Paintroid/src/main/java/org/catrobat/paintroid/command/CommandManager.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/AsyncCommandManager.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/ColorChangedCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/DefaultCommandManager.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/Tool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BrushTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ShapeTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/WatercolorTool.kt
- Paintroid/src/test/java/org/catrobat/paintroid/test/command/implementation/DefaultCommandManagerTest.kt
flashing of color preview removed (issue was for all tools)
-color is set to black before undo only if needed
-view is not always invalidated
[PAINTROID-530](https://jira.catrob.at/browse/PAINTROID-530)
> PAINTROID-530 Line tool color

- Jenkinsfile
*Fix the Pantroid pipeline via removing the Browserstack stage*
> DEVOPS-779 Revert Browserstack stage in Jenkinsfile

- Jenkinsfile
- Paintroid/src/main/java/org/catrobat/paintroid/ui/LayerAdapter.kt
Fixed the bug, where the opacity of the layers is reseted after a new layer is added  [Ticket](https://jira.catrob.at/browse/PAINTROID-651)
> PAINTROID-651 : Adding a new layer changes intensity of other layers

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/UndoRedoIntegrationTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/ColorChangedCommand.kt
- Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.kt
Eraser did not work properly when used with multiple layers, but this issue was already fixed
Ticket was used for fixing eraser issues when using ColorChanged Commands (as discussed with Thorsten). As the selected color should always be transparent, but changed when applying an undo action.
(https://jira.catrob.at/browse/PAINTROID-617)
> PAINTROID-617 eraser improvements

- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/LineToolTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/SprayToolTest.kt
- Paintroid/src/main/java/org/catrobat/paintroid/listener/DrawingSurfaceListener.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/Tool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BrushTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/FillTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/HandTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/PipetteTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SmudgeTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SprayTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.kt
- Paintroid/src/test/java/org/catrobat/paintroid/test/listener/DrawingSurfaceListenerTest.kt
Ticket: [PAINTROID-648](https://jira.catrob.at/browse/PAINTROID-648)
Added the threshold calculation to the handleMove method of Tool. Now it will only animate if the touchevent is within the first or last quarter of the devices display.
> PAINTROID-648 Dynamic animation of top and bottom bar

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/ShapeTool.kt
set higher strokeMiter threshold to avoid switching to bevel join prematurely
https://jira.catrob.at/browse/PAINTROID-699
> PAINTROID-699 Shape Tool: star tips missing in stroke mode

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithShape.kt
- Paintroid/src/main/res/values/colors.xml
Reduced alpha value of shape frame to 60% instead of 80% (80% does not make that much of a difference) for better visibility of drawing underneath
https://jira.catrob.at/browse/PAINTROID-652
> PAINTROID-652 Accessibility of shape frames

- Paintroid/src/main/java/org/catrobat/paintroid/LanguageHelper.kt
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/LayerAdapter.kt
- Paintroid/src/main/res/layout/dialog_pocketpaint_text_tool.xml
- Paintroid/src/main/res/layout/pocketpaint_layout_top_bar.xml
[PAINTROID-241](https://jira.catrob.at/browse/PAINTROID-241)
- Undo/Redo in top toolbar fixed for RTL languages according to Material Design.
- Undo/Redo arrows pointing in the right direction now according to Material Design.
- Undo/Redo in welcome screen fixed for RTL languages according to Material Design.
- Text Tool: fixed the icons and texts of icons according to Material Design. Also fixed the font size textinput.
- Created a new class called "LanguageHelper" that we can use in case we need to do language specific things like checking if the current language is a RTL language, for code reusability.
> PAINTROID-241 Layout errors in right-to-left languages

- Paintroid/build.gradle
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolIntegrationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.kt
- Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/UiInteractions.kt
- Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SprayTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/BrushToolView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultBrushToolOptionsView.kt
- Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultSmudgeToolOptionsView.kt
- build.gradle
https://jira.catrob.at/browse/PAINTROID-509 Fix org.catrobat.paintroid.test.espresso.tools
I added IdlingResource to several test files and flaky tests should now fail less often. 
The test testClickingOnCheckmarkDoesNotResetZoomOrPlacement was not testing the desired behaviour since it checked the surfaceTranslation to stay the same when in fact surfaceTranslation needs to change to not change placement.
I splitted the test into two new tests, one that only tests zoom and the other the placement. For the latter I had to update 
update Kotlin to 1.7.10 to use CaptureToBitmap functuality. It nows compares two bitmaps to check placement. However, the pixels that it compares to test the placement are not exactly the same and for that reason the pixel values have to be modified. The …
> PAINTROID-509 Fix org.catrobat.paintroid.test.espresso.tools

- Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BrushTool.kt
[PAINTROID-681](https://jira.catrob.at/browse/PAINTROID-681)
Fixed bug where eraser was weirdly readjusting the erased line causing a 2nd erased line to appear when removing the finger from the canvas. (after erasing was done)
> PAINTROID-681 Smoothing algorithm displays two lines (eraser tool)

- Paintroid/src/main/java/org/catrobat/paintroid/command/serialization/ClipboardCommandSerializer.kt
When the bitmap in the ClipboardCommandSerializer is null, an IOException instead of NullPointerException is thrown.  This exception is handled in FileIO.kt without crashing
https://jira.catrob.at/browse/PAINTROID-621
Should hopefully fix https://jira.catrob.at/browse/PAINTROID-600 too
> PAINTROID-621 Crash org.catrobat.paintroid.command.serialization.ClipboardCommandSerializer.readCurrentVersion
